2025-09-30 00:41:18.718 | ERROR    | __main__:<module>:215 - run_pipeline() missing 2 required positional arguments: 'interim_dir' and 'processed_dir'
Traceback (most recent call last):

  File "/usr/lib/python3.12/threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7c847a09a0c0>
    └ <Thread(ScriptRunner.scriptThread, started 136907496474304)>
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7c847a099da0>
    └ <Thread(ScriptRunner.scriptThread, started 136907496474304)>
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ScriptRunner.scriptThread, started 136907496474304)>
    │    │        │    └ ()
    │    │        └ <Thread(ScriptRunner.scriptThread, started 136907496474304)>
    │    └ <bound method ScriptRunner._run_script_thread of ScriptRunner(_session_id='43733ddf-0e8c-46e7-8144-32553f437507', _main_scrip...
    └ <Thread(ScriptRunner.scriptThread, started 136907496474304)>
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 378, in _run_script_thread
    self._run_script(request.rerun_data)
    │    │           │       └ <property object at 0x7c8478c63f10>
    │    │           └ ScriptRequest(type=<ScriptRequestType.RERUN: 'RERUN'>, _rerun_data=RerunData(widget_states=widgets {
    │    │               id: "$$ID-1e2cc8597619...
    │    └ <function ScriptRunner._run_script at 0x7c8478d3c860>
    └ ScriptRunner(_session_id='43733ddf-0e8c-46e7-8144-32553f437507', _main_script_path='src/web/app.py', _session_state={$$ID-946...
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 685, in _run_script
    ) = exec_func_with_error_handling(code_to_exec, ctx)
        │                             │             └ ScriptRunContext(session_id='43733ddf-0e8c-46e7-8144-32553f437507', _enqueue=<bound method ScriptRunner._enqueue_forward_msg ...
        │                             └ <function ScriptRunner._run_script.<locals>.code_to_exec at 0x7c8442b42520>
        └ <function exec_func_with_error_handling at 0x7c8478ce89a0>
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
             └ <function ScriptRunner._run_script.<locals>.code_to_exec at 0x7c8442b42520>
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
         │     │      └ <member '__dict__' of 'module' objects>
         │     └ <module '__main__' from 'src/web/app.py'>
         └ <code object <module> at 0x7c846001a5f0, file "/home/rishabh/Downloads/SIH-Project/src/web/app.py", line 1>

> File "/home/rishabh/Downloads/SIH-Project/src/web/app.py", line 205, in <module>
    meta = run_pipeline(str(tmp_cfg_path))
           │                └ PosixPath('/tmp/pipeline_override.yaml')
           └ <function run_pipeline at 0x7c8442d5b240>

TypeError: run_pipeline() missing 2 required positional arguments: 'interim_dir' and 'processed_dir'
2025-09-30 00:49:27.548 | ERROR    | __main__:<module>:227 - name 'uploaded_files_dir' is not defined
Traceback (most recent call last):

  File "/usr/lib/python3.12/threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x766803d9a0c0>
    └ <Thread(ScriptRunner.scriptThread, started 130188252804800)>
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x766803d99da0>
    └ <Thread(ScriptRunner.scriptThread, started 130188252804800)>
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ScriptRunner.scriptThread, started 130188252804800)>
    │    │        │    └ ()
    │    │        └ <Thread(ScriptRunner.scriptThread, started 130188252804800)>
    │    └ <bound method ScriptRunner._run_script_thread of ScriptRunner(_session_id='060637e3-37d5-458d-939a-a70b341a28b8', _main_scrip...
    └ <Thread(ScriptRunner.scriptThread, started 130188252804800)>
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 378, in _run_script_thread
    self._run_script(request.rerun_data)
    │    │           │       └ <property object at 0x766802c53f10>
    │    │           └ ScriptRequest(type=<ScriptRequestType.RERUN: 'RERUN'>, _rerun_data=RerunData(widget_states=widgets {
    │    │               id: "$$ID-946b940f3cb5...
    │    └ <function ScriptRunner._run_script at 0x766802b30860>
    └ ScriptRunner(_session_id='060637e3-37d5-458d-939a-a70b341a28b8', _main_script_path='src/web/app.py', _session_state={$$ID-946...
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 685, in _run_script
    ) = exec_func_with_error_handling(code_to_exec, ctx)
        │                             │             └ ScriptRunContext(session_id='060637e3-37d5-458d-939a-a70b341a28b8', _enqueue=<bound method ScriptRunner._enqueue_forward_msg ...
        │                             └ <function ScriptRunner._run_script.<locals>.code_to_exec at 0x7667d0929800>
        └ <function exec_func_with_error_handling at 0x766802adc9a0>
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
             └ <function ScriptRunner._run_script.<locals>.code_to_exec at 0x7667d0929800>
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
         │     │      └ <member '__dict__' of 'module' objects>
         │     └ <module '__main__' from 'src/web/app.py'>
         └ <code object <module> at 0x7667e8051c80, file "/home/rishabh/Downloads/SIH-Project/src/web/app.py", line 1>

> File "/home/rishabh/Downloads/SIH-Project/src/web/app.py", line 212, in <module>
    raw_dir=uploaded_files_dir,

NameError: name 'uploaded_files_dir' is not defined
2025-09-30 00:59:12.361 | ERROR    | __main__:<module>:227 - name 'k_value' is not defined
Traceback (most recent call last):

  File "/usr/lib/python3.12/threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x766803d9a0c0>
    └ <Thread(ScriptRunner.scriptThread, started 130188252804800)>
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x766803d99da0>
    └ <Thread(ScriptRunner.scriptThread, started 130188252804800)>
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ScriptRunner.scriptThread, started 130188252804800)>
    │    │        │    └ ()
    │    │        └ <Thread(ScriptRunner.scriptThread, started 130188252804800)>
    │    └ <bound method ScriptRunner._run_script_thread of ScriptRunner(_session_id='11115227-1ea6-461a-b9b7-e29882ba60c0', _main_scrip...
    └ <Thread(ScriptRunner.scriptThread, started 130188252804800)>
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 378, in _run_script_thread
    self._run_script(request.rerun_data)
    │    │           │       └ <property object at 0x766802c53f10>
    │    │           └ ScriptRequest(type=<ScriptRequestType.RERUN: 'RERUN'>, _rerun_data=RerunData(widget_states=widgets {
    │    │               id: "$$ID-946b940f3cb5...
    │    └ <function ScriptRunner._run_script at 0x766802b30860>
    └ ScriptRunner(_session_id='11115227-1ea6-461a-b9b7-e29882ba60c0', _main_script_path='src/web/app.py', _session_state={$$ID-946...
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 685, in _run_script
    ) = exec_func_with_error_handling(code_to_exec, ctx)
        │                             │             └ ScriptRunContext(session_id='11115227-1ea6-461a-b9b7-e29882ba60c0', _enqueue=<bound method ScriptRunner._enqueue_forward_msg ...
        │                             └ <function ScriptRunner._run_script.<locals>.code_to_exec at 0x7667d0929c60>
        └ <function exec_func_with_error_handling at 0x766802adc9a0>
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
             └ <function ScriptRunner._run_script.<locals>.code_to_exec at 0x7667d0929c60>
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
         │     │      └ <member '__dict__' of 'module' objects>
         │     └ <module '__main__' from 'src/web/app.py'>
         └ <code object <module> at 0x7667c4052440, file "/home/rishabh/Downloads/SIH-Project/src/web/app.py", line 1>

> File "/home/rishabh/Downloads/SIH-Project/src/web/app.py", line 216, in <module>
    k=k_value

NameError: name 'k_value' is not defined
2025-09-30 01:07:45.309 | INFO     | src.pipeline:run_pipeline:44 - Starting Stage 1 pipeline job with raw_dir=data/raw/fastq_dataset
2025-09-30 01:07:45.311 | INFO     | src.preprocessing.fastp_wrapper:run_fastp:62 - Running fastp: fastp -i data/raw/fastq_dataset/anc_R1.fastq -o /tmp/interim/anc_R1_clean.fastq.gz -w 4 -j /tmp/interim/fastp_report.json -h /tmp/interim/fastp_report.html -q 15 -l 50
2025-09-30 01:07:45.313 | ERROR    | __main__:<module>:227 - [Errno 2] No such file or directory: 'fastp'
Traceback (most recent call last):

  File "/usr/lib/python3.12/threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x76c973c71d00>
    └ <Thread(ScriptRunner.scriptThread, started 130606743680704)>
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x76c973c719e0>
    └ <Thread(ScriptRunner.scriptThread, started 130606743680704)>
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ScriptRunner.scriptThread, started 130606743680704)>
    │    │        │    └ ()
    │    │        └ <Thread(ScriptRunner.scriptThread, started 130606743680704)>
    │    └ <bound method ScriptRunner._run_script_thread of ScriptRunner(_session_id='08272879-8f3c-40f2-817c-f2584b3b0a03', _main_scrip...
    └ <Thread(ScriptRunner.scriptThread, started 130606743680704)>
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 378, in _run_script_thread
    self._run_script(request.rerun_data)
    │    │           │       └ <property object at 0x76c972a80590>
    │    │           └ ScriptRequest(type=<ScriptRequestType.RERUN: 'RERUN'>, _rerun_data=RerunData(widget_states=widgets {
    │    │               id: "$$ID-1e2cc8597619...
    │    └ <function ScriptRunner._run_script at 0x76c972b3c360>
    └ ScriptRunner(_session_id='08272879-8f3c-40f2-817c-f2584b3b0a03', _main_script_path='src/web/app.py', _session_state={$$ID-634...
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 685, in _run_script
    ) = exec_func_with_error_handling(code_to_exec, ctx)
        │                             │             └ ScriptRunContext(session_id='08272879-8f3c-40f2-817c-f2584b3b0a03', _enqueue=<bound method ScriptRunner._enqueue_forward_msg ...
        │                             └ <function ScriptRunner._run_script.<locals>.code_to_exec at 0x76c971459f80>
        └ <function exec_func_with_error_handling at 0x76c972ae04a0>
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
             └ <function ScriptRunner._run_script.<locals>.code_to_exec at 0x76c971459f80>
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
         │     │      └ <member '__dict__' of 'module' objects>
         │     └ <module '__main__' from 'src/web/app.py'>
         └ <code object <module> at 0x76c958052660, file "/home/rishabh/Downloads/SIH-Project/src/web/app.py", line 1>

> File "/home/rishabh/Downloads/SIH-Project/src/web/app.py", line 211, in <module>
    meta = run_pipeline(
           └ <function run_pipeline at 0x76c940ae2660>

  File "/home/rishabh/Downloads/SIH-Project/src/pipeline.py", line 64, in run_pipeline
    fastp_outputs = run_fastp(
                    └ <function run_fastp at 0x76c940ae20c0>

  File "/home/rishabh/Downloads/SIH-Project/src/preprocessing/fastp_wrapper.py", line 63, in run_fastp
    subprocess.run(cmd, check=True)
    │          │   └ ['fastp', '-i', 'data/raw/fastq_dataset/anc_R1.fastq', '-o', '/tmp/interim/anc_R1_clean.fastq.gz', '-w', '4', '-j', '/tmp/int...
    │          └ <function run at 0x76c973419760>
    └ <module 'subprocess' from '/usr/lib/python3.12/subprocess.py'>

  File "/usr/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         │      │            └ {}
         │      └ (['fastp', '-i', 'data/raw/fastq_dataset/anc_R1.fastq', '-o', '/tmp/interim/anc_R1_clean.fastq.gz', '-w', '4', '-j', '/tmp/in...
         └ <class 'subprocess.Popen'>
  File "/usr/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
    │    │              │     │           │           └ True
    │    │              │     │           └ None
    │    │              │     └ None
    │    │              └ ['fastp', '-i', 'data/raw/fastq_dataset/anc_R1.fastq', '-o', '/tmp/interim/anc_R1_clean.fastq.gz', '-w', '4', '-j', '/tmp/int...
    │    └ <function Popen._execute_child at 0x76c97341aac0>
    └ <Popen: returncode: 255 args: ['fastp', '-i', 'data/raw/fastq_dataset/anc_R1...>
  File "/usr/lib/python3.12/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
          │                    │          │        └ 'fastp'
          │                    │          └ 'No such file or directory'
          │                    └ 2
          └ <class 'OSError'>

FileNotFoundError: [Errno 2] No such file or directory: 'fastp'
2025-09-30 02:56:43.045 | INFO     | src.pipeline:run_pipeline:44 - Starting Stage 1 pipeline job with raw_dir=data/raw/fastq_dataset
2025-09-30 02:56:43.046 | INFO     | src.preprocessing.fastp_wrapper:run_fastp:62 - Running fastp: fastp -i data/raw/fastq_dataset/anc_R1.fastq -o /tmp/interim/anc_R1_clean.fastq.gz -w 4 -j /tmp/interim/fastp_report.json -h /tmp/interim/fastp_report.html -q 15 -l 50
2025-09-30 02:56:51.440 | INFO     | src.preprocessing.dada2_wrapper:run_dada2:31 - Running DADA2: Rscript scripts/run_dada2.R /tmp/interim dada2 /tmp/processed single 2 2 pseudo
2025-09-30 02:57:01.712 | ERROR    | __main__:<module>:227 - Command '['Rscript', 'scripts/run_dada2.R', '/tmp/interim', 'dada2', '/tmp/processed', 'single', '2', '2', 'pseudo']' returned non-zero exit status 1.
Traceback (most recent call last):

  File "/usr/lib/python3.12/threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x78c297871d00>
    └ <Thread(ScriptRunner.scriptThread, started 132776229598912)>
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x78c2978719e0>
    └ <Thread(ScriptRunner.scriptThread, started 132776229598912)>
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ScriptRunner.scriptThread, started 132776229598912)>
    │    │        │    └ ()
    │    │        └ <Thread(ScriptRunner.scriptThread, started 132776229598912)>
    │    └ <bound method ScriptRunner._run_script_thread of ScriptRunner(_session_id='7784cb8b-fc12-455e-bddc-18634bfec910', _main_scrip...
    └ <Thread(ScriptRunner.scriptThread, started 132776229598912)>
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 378, in _run_script_thread
    self._run_script(request.rerun_data)
    │    │           │       └ <property object at 0x78c29663cf40>
    │    │           └ ScriptRequest(type=<ScriptRequestType.RERUN: 'RERUN'>, _rerun_data=RerunData(widget_states=widgets {
    │    │               id: "$$ID-1e2cc8597619...
    │    └ <function ScriptRunner._run_script at 0x78c296700360>
    └ ScriptRunner(_session_id='7784cb8b-fc12-455e-bddc-18634bfec910', _main_script_path='src/web/app.py', _session_state={$$ID-634...
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 685, in _run_script
    ) = exec_func_with_error_handling(code_to_exec, ctx)
        │                             │             └ ScriptRunContext(session_id='7784cb8b-fc12-455e-bddc-18634bfec910', _enqueue=<bound method ScriptRunner._enqueue_forward_msg ...
        │                             └ <function ScriptRunner._run_script.<locals>.code_to_exec at 0x78c2644cd080>
        └ <function exec_func_with_error_handling at 0x78c2966a84a0>
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
             └ <function ScriptRunner._run_script.<locals>.code_to_exec at 0x78c2644cd080>
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
         │     │      └ <member '__dict__' of 'module' objects>
         │     └ <module '__main__' from 'src/web/app.py'>
         └ <code object <module> at 0x78c284052660, file "/home/rishabh/Downloads/SIH-Project/src/web/app.py", line 1>

> File "/home/rishabh/Downloads/SIH-Project/src/web/app.py", line 211, in <module>
    meta = run_pipeline(
           └ <function run_pipeline at 0x78c2646eeac0>

  File "/home/rishabh/Downloads/SIH-Project/src/pipeline.py", line 81, in run_pipeline
    dada2_outputs = run_dada2(
                    └ <function run_dada2 at 0x78c2646ee660>

  File "/home/rishabh/Downloads/SIH-Project/src/preprocessing/dada2_wrapper.py", line 32, in run_dada2
    subprocess.run(cmd, check=True)
    │          │   └ ['Rscript', 'scripts/run_dada2.R', '/tmp/interim', 'dada2', '/tmp/processed', 'single', '2', '2', 'pseudo']
    │          └ <function run at 0x78c297015760>
    └ <module 'subprocess' from '/usr/lib/python3.12/subprocess.py'>

  File "/usr/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
          │                  │        │       └ ['Rscript', 'scripts/run_dada2.R', '/tmp/interim', 'dada2', '/tmp/processed', 'single', '2', '2', 'pseudo']
          │                  │        └ <Popen: returncode: 1 args: ['Rscript', 'scripts/run_dada2.R', '/tmp/interim...>
          │                  └ 1
          └ <class 'subprocess.CalledProcessError'>

subprocess.CalledProcessError: Command '['Rscript', 'scripts/run_dada2.R', '/tmp/interim', 'dada2', '/tmp/processed', 'single', '2', '2', 'pseudo']' returned non-zero exit status 1.
2025-09-30 02:59:22.865 | INFO     | src.pipeline:run_pipeline:44 - Starting Stage 1 pipeline job with raw_dir=data/raw/fastq_dataset
2025-09-30 02:59:22.866 | INFO     | src.preprocessing.fastp_wrapper:run_fastp:62 - Running fastp: fastp -i data/raw/fastq_dataset/anc_R1.fastq -o /tmp/interim/anc_R1_clean.fastq.gz -w 4 -j /tmp/interim/fastp_report.json -h /tmp/interim/fastp_report.html -q 15 -l 50
2025-09-30 02:59:32.024 | INFO     | src.preprocessing.dada2_wrapper:run_dada2:31 - Running DADA2: Rscript scripts/run_dada2.R /tmp/interim dada2 /tmp/processed single 2 2 pseudo
2025-09-30 02:59:55.271 | ERROR    | __main__:<module>:227 - Command '['Rscript', 'scripts/run_dada2.R', '/tmp/interim', 'dada2', '/tmp/processed', 'single', '2', '2', 'pseudo']' returned non-zero exit status 1.
Traceback (most recent call last):

  File "/usr/lib/python3.12/threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7c9e79171d00>
    └ <Thread(ScriptRunner.scriptThread, started 137019218482880)>
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7c9e791719e0>
    └ <Thread(ScriptRunner.scriptThread, started 137019218482880)>
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ScriptRunner.scriptThread, started 137019218482880)>
    │    │        │    └ ()
    │    │        └ <Thread(ScriptRunner.scriptThread, started 137019218482880)>
    │    └ <bound method ScriptRunner._run_script_thread of ScriptRunner(_session_id='95d74f51-d852-420a-b1c0-29ea0fc91112', _main_scrip...
    └ <Thread(ScriptRunner.scriptThread, started 137019218482880)>
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 378, in _run_script_thread
    self._run_script(request.rerun_data)
    │    │           │       └ <property object at 0x7c9e77f08f40>
    │    │           └ ScriptRequest(type=<ScriptRequestType.RERUN: 'RERUN'>, _rerun_data=RerunData(widget_states=widgets {
    │    │               id: "$$ID-946b940f3cb5...
    │    └ <function ScriptRunner._run_script at 0x7c9e77fcc360>
    └ ScriptRunner(_session_id='95d74f51-d852-420a-b1c0-29ea0fc91112', _main_script_path='src/web/app.py', _session_state={$$ID-946...
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 685, in _run_script
    ) = exec_func_with_error_handling(code_to_exec, ctx)
        │                             │             └ ScriptRunContext(session_id='95d74f51-d852-420a-b1c0-29ea0fc91112', _enqueue=<bound method ScriptRunner._enqueue_forward_msg ...
        │                             └ <function ScriptRunner._run_script.<locals>.code_to_exec at 0x7c9e45fb7c40>
        └ <function exec_func_with_error_handling at 0x7c9e77f784a0>
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
             └ <function ScriptRunner._run_script.<locals>.code_to_exec at 0x7c9e45fb7c40>
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
         │     │      └ <member '__dict__' of 'module' objects>
         │     └ <module '__main__' from 'src/web/app.py'>
         └ <code object <module> at 0x7c9e60052650, file "/home/rishabh/Downloads/SIH-Project/src/web/app.py", line 1>

> File "/home/rishabh/Downloads/SIH-Project/src/web/app.py", line 211, in <module>
    meta = run_pipeline(
           └ <function run_pipeline at 0x7c9e45f76ac0>

  File "/home/rishabh/Downloads/SIH-Project/src/pipeline.py", line 81, in run_pipeline
    dada2_outputs = run_dada2(
                    └ <function run_dada2 at 0x7c9e45f76660>

  File "/home/rishabh/Downloads/SIH-Project/src/preprocessing/dada2_wrapper.py", line 32, in run_dada2
    subprocess.run(cmd, check=True)
    │          │   └ ['Rscript', 'scripts/run_dada2.R', '/tmp/interim', 'dada2', '/tmp/processed', 'single', '2', '2', 'pseudo']
    │          └ <function run at 0x7c9e78915760>
    └ <module 'subprocess' from '/usr/lib/python3.12/subprocess.py'>

  File "/usr/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
          │                  │        │       └ ['Rscript', 'scripts/run_dada2.R', '/tmp/interim', 'dada2', '/tmp/processed', 'single', '2', '2', 'pseudo']
          │                  │        └ <Popen: returncode: 1 args: ['Rscript', 'scripts/run_dada2.R', '/tmp/interim...>
          │                  └ 1
          └ <class 'subprocess.CalledProcessError'>

subprocess.CalledProcessError: Command '['Rscript', 'scripts/run_dada2.R', '/tmp/interim', 'dada2', '/tmp/processed', 'single', '2', '2', 'pseudo']' returned non-zero exit status 1.
2025-09-30 03:39:08.057 | INFO     | src.pipeline:run_pipeline:44 - Starting Stage 1 pipeline job with raw_dir=data/raw/fastq_dataset
2025-09-30 03:39:08.059 | INFO     | src.preprocessing.fastp_wrapper:run_fastp:62 - Running fastp: fastp -i data/raw/fastq_dataset/anc_R1.fastq -o /tmp/interim/anc_R1_clean.fastq.gz -w 4 -j /tmp/interim/fastp_report.json -h /tmp/interim/fastp_report.html -q 15 -l 50
2025-09-30 03:39:16.816 | INFO     | src.preprocessing.dada2_wrapper:run_dada2:31 - Running DADA2: Rscript scripts/run_dada2.R /tmp/interim dada2 /tmp/processed single 2 2 pseudo
2025-09-30 03:39:27.330 | INFO     | src.pipeline:run_pipeline:121 - Metadata written to /tmp/processed/stage1_metadata.json
2025-09-30 03:40:57.991 | INFO     | src.pipeline:run_pipeline:44 - Starting Stage 1 pipeline job with raw_dir=data/raw/fastq_dataset
2025-09-30 03:40:57.992 | INFO     | src.preprocessing.fastp_wrapper:run_fastp:62 - Running fastp: fastp -i data/raw/fastq_dataset/anc_R1.fastq -I data/raw/fastq_dataset/anc_R2.fastq -o /tmp/interim/anc_R1_clean.fastq.gz -O /tmp/interim/anc_R2_clean.fastq.gz -w 4 -j /tmp/interim/fastp_report.json -h /tmp/interim/fastp_report.html -q 15 -l 50 --detect_adapter_for_pe
2025-09-30 03:41:14.836 | INFO     | src.preprocessing.dada2_wrapper:run_dada2:31 - Running DADA2: Rscript scripts/run_dada2.R /tmp/interim dada2 /tmp/processed paired 2 2 pseudo
2025-09-30 03:41:35.481 | ERROR    | __main__:<module>:227 - Command '['Rscript', 'scripts/run_dada2.R', '/tmp/interim', 'dada2', '/tmp/processed', 'paired', '2', '2', 'pseudo']' returned non-zero exit status 1.
Traceback (most recent call last):

  File "/usr/lib/python3.12/threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x74a857171d00>
    └ <Thread(ScriptRunner.scriptThread, started 128265437722304)>
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x74a8571719e0>
    └ <Thread(ScriptRunner.scriptThread, started 128265437722304)>
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ScriptRunner.scriptThread, started 128265437722304)>
    │    │        │    └ ()
    │    │        └ <Thread(ScriptRunner.scriptThread, started 128265437722304)>
    │    └ <bound method ScriptRunner._run_script_thread of ScriptRunner(_session_id='1288fc0b-a4f8-40c6-9f2b-e4b34af487d1', _main_scrip...
    └ <Thread(ScriptRunner.scriptThread, started 128265437722304)>
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 378, in _run_script_thread
    self._run_script(request.rerun_data)
    │    │           │       └ <property object at 0x74a855f74f40>
    │    │           └ ScriptRequest(type=<ScriptRequestType.RERUN: 'RERUN'>, _rerun_data=RerunData(widget_states=widgets {
    │    │               id: "$$ID-946b940f3cb5...
    │    └ <function ScriptRunner._run_script at 0x74a856038360>
    └ ScriptRunner(_session_id='1288fc0b-a4f8-40c6-9f2b-e4b34af487d1', _main_script_path='src/web/app.py', _session_state={$$STREAM...
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 685, in _run_script
    ) = exec_func_with_error_handling(code_to_exec, ctx)
        │                             │             └ ScriptRunContext(session_id='1288fc0b-a4f8-40c6-9f2b-e4b34af487d1', _enqueue=<bound method ScriptRunner._enqueue_forward_msg ...
        │                             └ <function ScriptRunner._run_script.<locals>.code_to_exec at 0x74a854959f80>
        └ <function exec_func_with_error_handling at 0x74a855fe04a0>
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
             └ <function ScriptRunner._run_script.<locals>.code_to_exec at 0x74a854959f80>
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
         │     │      └ <member '__dict__' of 'module' objects>
         │     └ <module '__main__' from 'src/web/app.py'>
         └ <code object <module> at 0x74a844052660, file "/home/rishabh/Downloads/SIH-Project/src/web/app.py", line 1>

> File "/home/rishabh/Downloads/SIH-Project/src/web/app.py", line 211, in <module>
    meta = run_pipeline(
           └ <function run_pipeline at 0x74a81ffe2ac0>

  File "/home/rishabh/Downloads/SIH-Project/src/pipeline.py", line 81, in run_pipeline
    dada2_outputs = run_dada2(
                    └ <function run_dada2 at 0x74a81ffe2660>

  File "/home/rishabh/Downloads/SIH-Project/src/preprocessing/dada2_wrapper.py", line 32, in run_dada2
    subprocess.run(cmd, check=True)
    │          │   └ ['Rscript', 'scripts/run_dada2.R', '/tmp/interim', 'dada2', '/tmp/processed', 'paired', '2', '2', 'pseudo']
    │          └ <function run at 0x74a856915760>
    └ <module 'subprocess' from '/usr/lib/python3.12/subprocess.py'>

  File "/usr/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
          │                  │        │       └ ['Rscript', 'scripts/run_dada2.R', '/tmp/interim', 'dada2', '/tmp/processed', 'paired', '2', '2', 'pseudo']
          │                  │        └ <Popen: returncode: 1 args: ['Rscript', 'scripts/run_dada2.R', '/tmp/interim...>
          │                  └ 1
          └ <class 'subprocess.CalledProcessError'>

subprocess.CalledProcessError: Command '['Rscript', 'scripts/run_dada2.R', '/tmp/interim', 'dada2', '/tmp/processed', 'paired', '2', '2', 'pseudo']' returned non-zero exit status 1.
2025-09-30 03:42:28.050 | INFO     | src.pipeline:run_pipeline:44 - Starting Stage 1 pipeline job with raw_dir=data/raw/fastq_dataset
2025-09-30 03:42:28.051 | INFO     | src.preprocessing.fastp_wrapper:run_fastp:62 - Running fastp: fastp -i data/raw/fastq_dataset/anc_R1.fastq -I data/raw/fastq_dataset/anc_R2.fastq -o /tmp/interim/anc_R1_clean.fastq.gz -O /tmp/interim/anc_R2_clean.fastq.gz -w 4 -j /tmp/interim/fastp_report.json -h /tmp/interim/fastp_report.html -q 15 -l 50 --detect_adapter_for_pe
2025-09-30 03:42:43.678 | INFO     | src.preprocessing.dada2_wrapper:run_dada2:31 - Running DADA2: Rscript scripts/run_dada2.R /tmp/interim dada2 /tmp/processed paired 2 2 pseudo
2025-09-30 03:43:02.764 | ERROR    | __main__:<module>:227 - Command '['Rscript', 'scripts/run_dada2.R', '/tmp/interim', 'dada2', '/tmp/processed', 'paired', '2', '2', 'pseudo']' returned non-zero exit status 1.
Traceback (most recent call last):

  File "/usr/lib/python3.12/threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x74a857171d00>
    └ <Thread(ScriptRunner.scriptThread, started 128265387366080)>
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x74a8571719e0>
    └ <Thread(ScriptRunner.scriptThread, started 128265387366080)>
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ScriptRunner.scriptThread, started 128265387366080)>
    │    │        │    └ ()
    │    │        └ <Thread(ScriptRunner.scriptThread, started 128265387366080)>
    │    └ <bound method ScriptRunner._run_script_thread of ScriptRunner(_session_id='1288fc0b-a4f8-40c6-9f2b-e4b34af487d1', _main_scrip...
    └ <Thread(ScriptRunner.scriptThread, started 128265387366080)>
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 378, in _run_script_thread
    self._run_script(request.rerun_data)
    │    │           │       └ <property object at 0x74a855f74f40>
    │    │           └ ScriptRequest(type=<ScriptRequestType.RERUN: 'RERUN'>, _rerun_data=RerunData(widget_states=widgets {
    │    │               id: "$$ID-946b940f3cb5...
    │    └ <function ScriptRunner._run_script at 0x74a856038360>
    └ ScriptRunner(_session_id='1288fc0b-a4f8-40c6-9f2b-e4b34af487d1', _main_script_path='src/web/app.py', _session_state={$$STREAM...
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 685, in _run_script
    ) = exec_func_with_error_handling(code_to_exec, ctx)
        │                             │             └ ScriptRunContext(session_id='1288fc0b-a4f8-40c6-9f2b-e4b34af487d1', _enqueue=<bound method ScriptRunner._enqueue_forward_msg ...
        │                             └ <function ScriptRunner._run_script.<locals>.code_to_exec at 0x74a854ae7ce0>
        └ <function exec_func_with_error_handling at 0x74a855fe04a0>
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
             └ <function ScriptRunner._run_script.<locals>.code_to_exec at 0x74a854ae7ce0>
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
         │     │      └ <member '__dict__' of 'module' objects>
         │     └ <module '__main__' from 'src/web/app.py'>
         └ <code object <module> at 0x74a844052660, file "/home/rishabh/Downloads/SIH-Project/src/web/app.py", line 1>

> File "/home/rishabh/Downloads/SIH-Project/src/web/app.py", line 211, in <module>
    meta = run_pipeline(
           └ <function run_pipeline at 0x74a81ffe2ac0>

  File "/home/rishabh/Downloads/SIH-Project/src/pipeline.py", line 81, in run_pipeline
    dada2_outputs = run_dada2(
                    └ <function run_dada2 at 0x74a81ffe2660>

  File "/home/rishabh/Downloads/SIH-Project/src/preprocessing/dada2_wrapper.py", line 32, in run_dada2
    subprocess.run(cmd, check=True)
    │          │   └ ['Rscript', 'scripts/run_dada2.R', '/tmp/interim', 'dada2', '/tmp/processed', 'paired', '2', '2', 'pseudo']
    │          └ <function run at 0x74a856915760>
    └ <module 'subprocess' from '/usr/lib/python3.12/subprocess.py'>

  File "/usr/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
          │                  │        │       └ ['Rscript', 'scripts/run_dada2.R', '/tmp/interim', 'dada2', '/tmp/processed', 'paired', '2', '2', 'pseudo']
          │                  │        └ <Popen: returncode: 1 args: ['Rscript', 'scripts/run_dada2.R', '/tmp/interim...>
          │                  └ 1
          └ <class 'subprocess.CalledProcessError'>

subprocess.CalledProcessError: Command '['Rscript', 'scripts/run_dada2.R', '/tmp/interim', 'dada2', '/tmp/processed', 'paired', '2', '2', 'pseudo']' returned non-zero exit status 1.
2025-09-30 03:43:24.468 | INFO     | src.pipeline:run_pipeline:44 - Starting Stage 1 pipeline job with raw_dir=data/raw/fastq_dataset
2025-09-30 03:43:24.469 | INFO     | src.preprocessing.fastp_wrapper:run_fastp:62 - Running fastp: fastp -i data/raw/fastq_dataset/anc_R1.fastq -I data/raw/fastq_dataset/anc_R2.fastq -o /tmp/interim/anc_R1_clean.fastq.gz -O /tmp/interim/anc_R2_clean.fastq.gz -w 4 -j /tmp/interim/fastp_report.json -h /tmp/interim/fastp_report.html -q 15 -l 50 --detect_adapter_for_pe
2025-09-30 03:43:39.112 | INFO     | src.preprocessing.dada2_wrapper:run_dada2:31 - Running DADA2: Rscript scripts/run_dada2.R /tmp/interim dada2 /tmp/processed paired 2 2 pseudo
2025-09-30 03:43:57.191 | ERROR    | __main__:<module>:227 - Command '['Rscript', 'scripts/run_dada2.R', '/tmp/interim', 'dada2', '/tmp/processed', 'paired', '2', '2', 'pseudo']' returned non-zero exit status 1.
Traceback (most recent call last):

  File "/usr/lib/python3.12/threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x74a857171d00>
    └ <Thread(ScriptRunner.scriptThread, started 128265387366080)>
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x74a8571719e0>
    └ <Thread(ScriptRunner.scriptThread, started 128265387366080)>
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ScriptRunner.scriptThread, started 128265387366080)>
    │    │        │    └ ()
    │    │        └ <Thread(ScriptRunner.scriptThread, started 128265387366080)>
    │    └ <bound method ScriptRunner._run_script_thread of ScriptRunner(_session_id='1288fc0b-a4f8-40c6-9f2b-e4b34af487d1', _main_scrip...
    └ <Thread(ScriptRunner.scriptThread, started 128265387366080)>
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 378, in _run_script_thread
    self._run_script(request.rerun_data)
    │    │           │       └ <property object at 0x74a855f74f40>
    │    │           └ ScriptRequest(type=<ScriptRequestType.RERUN: 'RERUN'>, _rerun_data=RerunData(widget_states=widgets {
    │    │               id: "$$ID-946b940f3cb5...
    │    └ <function ScriptRunner._run_script at 0x74a856038360>
    └ ScriptRunner(_session_id='1288fc0b-a4f8-40c6-9f2b-e4b34af487d1', _main_script_path='src/web/app.py', _session_state={$$STREAM...
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 685, in _run_script
    ) = exec_func_with_error_handling(code_to_exec, ctx)
        │                             │             └ ScriptRunContext(session_id='1288fc0b-a4f8-40c6-9f2b-e4b34af487d1', _enqueue=<bound method ScriptRunner._enqueue_forward_msg ...
        │                             └ <function ScriptRunner._run_script.<locals>.code_to_exec at 0x74a854ae7e20>
        └ <function exec_func_with_error_handling at 0x74a855fe04a0>
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
             └ <function ScriptRunner._run_script.<locals>.code_to_exec at 0x74a854ae7e20>
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
         │     │      └ <member '__dict__' of 'module' objects>
         │     └ <module '__main__' from 'src/web/app.py'>
         └ <code object <module> at 0x74a844052660, file "/home/rishabh/Downloads/SIH-Project/src/web/app.py", line 1>

> File "/home/rishabh/Downloads/SIH-Project/src/web/app.py", line 211, in <module>
    meta = run_pipeline(
           └ <function run_pipeline at 0x74a81ffe2ac0>

  File "/home/rishabh/Downloads/SIH-Project/src/pipeline.py", line 81, in run_pipeline
    dada2_outputs = run_dada2(
                    └ <function run_dada2 at 0x74a81ffe2660>

  File "/home/rishabh/Downloads/SIH-Project/src/preprocessing/dada2_wrapper.py", line 32, in run_dada2
    subprocess.run(cmd, check=True)
    │          │   └ ['Rscript', 'scripts/run_dada2.R', '/tmp/interim', 'dada2', '/tmp/processed', 'paired', '2', '2', 'pseudo']
    │          └ <function run at 0x74a856915760>
    └ <module 'subprocess' from '/usr/lib/python3.12/subprocess.py'>

  File "/usr/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
          │                  │        │       └ ['Rscript', 'scripts/run_dada2.R', '/tmp/interim', 'dada2', '/tmp/processed', 'paired', '2', '2', 'pseudo']
          │                  │        └ <Popen: returncode: 1 args: ['Rscript', 'scripts/run_dada2.R', '/tmp/interim...>
          │                  └ 1
          └ <class 'subprocess.CalledProcessError'>

subprocess.CalledProcessError: Command '['Rscript', 'scripts/run_dada2.R', '/tmp/interim', 'dada2', '/tmp/processed', 'paired', '2', '2', 'pseudo']' returned non-zero exit status 1.
2025-09-30 04:02:35.724 | INFO     | src.pipeline:run_pipeline:44 - Starting Stage 1 pipeline job with raw_dir=data/raw/fastq_dataset
2025-09-30 04:02:35.725 | INFO     | src.preprocessing.fastp_wrapper:run_fastp:62 - Running fastp: fastp -i data/raw/fastq_dataset/anc_R1.fastq -I data/raw/fastq_dataset/anc_R2.fastq -o /tmp/interim/anc_R1_clean.fastq.gz -O /tmp/interim/anc_R2_clean.fastq.gz -w 4 -j /tmp/interim/fastp_report.json -h /tmp/interim/fastp_report.html -q 15 -l 50 --detect_adapter_for_pe
2025-09-30 04:02:52.620 | INFO     | src.preprocessing.dada2_wrapper:run_dada2:31 - Running DADA2: Rscript scripts/run_dada2.R /tmp/interim dada2 /tmp/processed paired 2 2 pseudo
2025-09-30 04:03:04.846 | INFO     | src.pipeline:run_pipeline:121 - Metadata written to /tmp/processed/stage1_metadata.json
2025-09-30 04:12:36.705 | INFO     | src.pipeline:run_pipeline:44 - Starting Stage 1 pipeline job with raw_dir=data/raw/fastq_dataset
2025-09-30 04:12:36.706 | INFO     | src.preprocessing.fastp_wrapper:run_fastp:62 - Running fastp: fastp -i data/raw/fastq_dataset/anc_R1.fastq -I data/raw/fastq_dataset/anc_R2.fastq -o /tmp/interim/anc_R1_clean.fastq.gz -O /tmp/interim/anc_R2_clean.fastq.gz -w 4 -j /tmp/interim/fastp_report.json -h /tmp/interim/fastp_report.html -q 15 -l 50 --detect_adapter_for_pe
2025-09-30 04:12:52.389 | INFO     | src.preprocessing.dada2_wrapper:run_dada2:31 - Running DADA2: Rscript scripts/run_dada2.R /tmp/interim dada2 /tmp/processed paired 2 2 pseudo
2025-09-30 04:13:02.779 | INFO     | src.pipeline:run_pipeline:121 - Metadata written to /tmp/processed/stage1_metadata.json
2025-09-30 04:13:41.776 | INFO     | src.pipeline:run_pipeline:44 - Starting Stage 1 pipeline job with raw_dir=data/raw/fastq_dataset
2025-09-30 04:13:41.777 | INFO     | src.preprocessing.fastp_wrapper:run_fastp:62 - Running fastp: fastp -i data/raw/fastq_dataset/anc_R1.fastq -I data/raw/fastq_dataset/anc_R2.fastq -o /tmp/interim/anc_R1_clean.fastq.gz -O /tmp/interim/anc_R2_clean.fastq.gz -w 4 -j /tmp/interim/fastp_report.json -h /tmp/interim/fastp_report.html -q 15 -l 50 --detect_adapter_for_pe
2025-09-30 04:13:57.305 | INFO     | src.preprocessing.dada2_wrapper:run_dada2:31 - Running DADA2: Rscript scripts/run_dada2.R /tmp/interim dada2 /tmp/processed paired 2 2 pseudo
2025-09-30 04:14:07.566 | INFO     | src.pipeline:run_pipeline:121 - Metadata written to /tmp/processed/stage1_metadata.json
2025-09-30 04:14:24.045 | INFO     | src.pipeline:run_pipeline:44 - Starting Stage 1 pipeline job with raw_dir=data/raw/fastq_dataset
2025-09-30 04:14:24.046 | INFO     | src.preprocessing.fastp_wrapper:run_fastp:62 - Running fastp: fastp -i data/raw/fastq_dataset/anc_R1.fastq -I data/raw/fastq_dataset/anc_R2.fastq -o /tmp/interim/anc_R1_clean.fastq.gz -O /tmp/interim/anc_R2_clean.fastq.gz -w 4 -j /tmp/interim/fastp_report.json -h /tmp/interim/fastp_report.html -q 15 -l 50 --detect_adapter_for_pe
2025-09-30 04:14:39.085 | INFO     | src.preprocessing.dada2_wrapper:run_dada2:31 - Running DADA2: Rscript scripts/run_dada2.R /tmp/interim dada2 /tmp/processed paired 2 2 pseudo
2025-09-30 04:14:49.779 | INFO     | src.pipeline:run_pipeline:121 - Metadata written to /tmp/processed/stage1_metadata.json
2025-09-30 04:15:39.483 | INFO     | src.pipeline:run_pipeline:44 - Starting Stage 1 pipeline job with raw_dir=data/raw/fastq_dataset
2025-09-30 04:15:39.483 | INFO     | src.preprocessing.fastp_wrapper:run_fastp:62 - Running fastp: fastp -i data/raw/fastq_dataset/anc_R1.fastq -I data/raw/fastq_dataset/anc_R2.fastq -o /tmp/interim/anc_R1_clean.fastq.gz -O /tmp/interim/anc_R2_clean.fastq.gz -w 4 -j /tmp/interim/fastp_report.json -h /tmp/interim/fastp_report.html -q 15 -l 50 --detect_adapter_for_pe
2025-09-30 04:15:54.997 | INFO     | src.preprocessing.dada2_wrapper:run_dada2:31 - Running DADA2: Rscript scripts/run_dada2.R /tmp/interim dada2 /tmp/processed paired 2 2 pseudo
2025-09-30 04:16:05.330 | INFO     | src.pipeline:run_pipeline:121 - Metadata written to /tmp/processed/stage1_metadata.json
2025-09-30 05:04:32.291 | INFO     | pipeline:run_pipeline:44 - Starting Stage 1 pipeline job with raw_dir=fastq_dataset
2025-09-30 05:04:32.292 | INFO     | src.preprocessing.fastp_wrapper:run_fastp:62 - Running fastp: fastp -i fastq_dataset/anc_R1.fastq -I fastq_dataset/anc_R2.fastq -o /tmp/interim/anc_R1_clean.fastq.gz -O /tmp/interim/anc_R2_clean.fastq.gz -w 4 -j /tmp/interim/fastp_report.json -h /tmp/interim/fastp_report.html -q 15 -l 50 --detect_adapter_for_pe
2025-09-30 05:04:49.574 | INFO     | src.preprocessing.dada2_wrapper:run_dada2:31 - Running DADA2: Rscript scripts/run_dada2.R /tmp/interim dada2 /tmp/processed paired 2 2 pseudo
2025-09-30 05:13:57.556 | INFO     | pipeline:run_pipeline:44 - Starting Stage 1 pipeline job with raw_dir=/tmp/test_raw
2025-09-30 05:13:57.556 | INFO     | src.preprocessing.fastp_wrapper:run_fastp:62 - Running fastp: fastp -i /tmp/test_raw/sample.fastq -o /tmp/test_interim/sample_clean.fastq.gz -w 4 -j /tmp/test_interim/fastp_report.json -h /tmp/test_interim/fastp_report.html -q 15 -l 50
2025-09-30 05:15:12.471 | INFO     | pipeline:run_pipeline:44 - Starting Stage 1 pipeline job with raw_dir=/tmp/test_raw
2025-09-30 05:15:12.472 | INFO     | src.preprocessing.fastp_wrapper:run_fastp:62 - Running fastp: fastp -i /tmp/test_raw/sample_fixed.fastq -o /tmp/test_interim/sample_fixed_clean.fastq.gz -w 4 -j /tmp/test_interim/fastp_report.json -h /tmp/test_interim/fastp_report.html -q 15 -l 50
2025-09-30 05:15:13.369 | INFO     | src.preprocessing.dada2_wrapper:run_dada2:31 - Running DADA2: Rscript scripts/run_dada2.R /tmp/test_interim dada2 /tmp/test_processed single 2 2 pseudo
2025-09-30 05:15:26.922 | INFO     | pipeline:run_pipeline:121 - Metadata written to /tmp/test_processed/stage1_metadata.json
2025-09-30 05:53:42.787 | INFO     | src.pipeline:run_pipeline:44 - Starting Stage 1 pipeline job with raw_dir=data/raw/fastq_dataset
2025-09-30 05:53:42.790 | INFO     | src.preprocessing.fastp_wrapper:run_fastp:62 - Running fastp: fastp -i data/raw/fastq_dataset/anc_R1.fastq -I data/raw/fastq_dataset/anc_R2.fastq -o /tmp/interim/anc_R1_clean.fastq.gz -O /tmp/interim/anc_R2_clean.fastq.gz -w 4 -j /tmp/interim/fastp_report.json -h /tmp/interim/fastp_report.html -q 15 -l 50 --detect_adapter_for_pe
2025-09-30 05:54:07.106 | INFO     | src.preprocessing.dada2_wrapper:run_dada2:31 - Running DADA2: Rscript scripts/run_dada2.R /tmp/interim dada2 /tmp/processed paired 2 2 pseudo
2025-09-30 05:54:38.586 | ERROR    | __main__:<module>:227 - Command '['Rscript', 'scripts/run_dada2.R', '/tmp/interim', 'dada2', '/tmp/processed', 'paired', '2', '2', 'pseudo']' returned non-zero exit status 1.
Traceback (most recent call last):

  File "/usr/lib/python3.12/threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7d1ede971d00>
    └ <Thread(ScriptRunner.scriptThread, started 137570610198208)>
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7d1ede9719e0>
    └ <Thread(ScriptRunner.scriptThread, started 137570610198208)>
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ScriptRunner.scriptThread, started 137570610198208)>
    │    │        │    └ ()
    │    │        └ <Thread(ScriptRunner.scriptThread, started 137570610198208)>
    │    └ <bound method ScriptRunner._run_script_thread of ScriptRunner(_session_id='32d2fc5c-0326-4e2d-bf11-d528add5280a', _main_scrip...
    └ <Thread(ScriptRunner.scriptThread, started 137570610198208)>
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 378, in _run_script_thread
    self._run_script(request.rerun_data)
    │    │           │       └ <property object at 0x7d1edd775350>
    │    │           └ ScriptRequest(type=<ScriptRequestType.RERUN: 'RERUN'>, _rerun_data=RerunData(widget_states=widgets {
    │    │               id: "$$ID-1e2cc8597619...
    │    └ <function ScriptRunner._run_script at 0x7d1edd838360>
    └ ScriptRunner(_session_id='32d2fc5c-0326-4e2d-bf11-d528add5280a', _main_script_path='src/web/app.py', _session_state={$$ID-946...
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 685, in _run_script
    ) = exec_func_with_error_handling(code_to_exec, ctx)
        │                             │             └ ScriptRunContext(session_id='32d2fc5c-0326-4e2d-bf11-d528add5280a', _enqueue=<bound method ScriptRunner._enqueue_forward_msg ...
        │                             └ <function ScriptRunner._run_script.<locals>.code_to_exec at 0x7d1ea75c5080>
        └ <function exec_func_with_error_handling at 0x7d1edd7e04a0>
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
             └ <function ScriptRunner._run_script.<locals>.code_to_exec at 0x7d1ea75c5080>
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
         │     │      └ <member '__dict__' of 'module' objects>
         │     └ <module '__main__' from 'src/web/app.py'>
         └ <code object <module> at 0x7d1ec4052650, file "/home/rishabh/Downloads/SIH-Project/src/web/app.py", line 1>

> File "/home/rishabh/Downloads/SIH-Project/src/web/app.py", line 211, in <module>
    meta = run_pipeline(
           └ <function run_pipeline at 0x7d1ea77e6b60>

  File "/home/rishabh/Downloads/SIH-Project/src/pipeline.py", line 81, in run_pipeline
    dada2_outputs = run_dada2(
                    └ <function run_dada2 at 0x7d1ea77e6700>

  File "/home/rishabh/Downloads/SIH-Project/src/preprocessing/dada2_wrapper.py", line 32, in run_dada2
    subprocess.run(cmd, check=True)
    │          │   └ ['Rscript', 'scripts/run_dada2.R', '/tmp/interim', 'dada2', '/tmp/processed', 'paired', '2', '2', 'pseudo']
    │          └ <function run at 0x7d1ede115760>
    └ <module 'subprocess' from '/usr/lib/python3.12/subprocess.py'>

  File "/usr/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
          │                  │        │       └ ['Rscript', 'scripts/run_dada2.R', '/tmp/interim', 'dada2', '/tmp/processed', 'paired', '2', '2', 'pseudo']
          │                  │        └ <Popen: returncode: 1 args: ['Rscript', 'scripts/run_dada2.R', '/tmp/interim...>
          │                  └ 1
          └ <class 'subprocess.CalledProcessError'>

subprocess.CalledProcessError: Command '['Rscript', 'scripts/run_dada2.R', '/tmp/interim', 'dada2', '/tmp/processed', 'paired', '2', '2', 'pseudo']' returned non-zero exit status 1.
2025-09-30 12:47:58.088 | INFO     | pipeline:run_pipeline:44 - Starting Stage 1 pipeline job with raw_dir=/tmp/test_raw
2025-09-30 12:47:58.090 | INFO     | src.preprocessing.fastp_wrapper:run_fastp:62 - Running fastp: fastp -i /tmp/test_raw/sample.fastq -o /tmp/test_interim/sample_clean.fastq.gz -w 4 -j /tmp/test_interim/fastp_report.json -h /tmp/test_interim/fastp_report.html -q 15 -l 50
2025-09-30 12:50:40.601 | INFO     | pipeline:run_pipeline:44 - Starting Stage 1 pipeline job with raw_dir=/tmp/test_raw
2025-09-30 12:50:40.603 | INFO     | src.preprocessing.fastp_wrapper:run_fastp:62 - Running fastp: fastp -i /tmp/test_raw/sample_fixed.fastq -o /tmp/test_interim/sample_fixed_clean.fastq.gz -w 4 -j /tmp/test_interim/fastp_report.json -h /tmp/test_interim/fastp_report.html -q 15 -l 50
2025-09-30 12:50:42.170 | INFO     | src.preprocessing.dada2_wrapper:run_dada2:31 - Running DADA2: Rscript scripts/run_dada2.R /tmp/test_interim dada2 /tmp/test_processed single 2 2 pseudo
2025-09-30 12:54:14.948 | INFO     | pipeline:run_pipeline:44 - Starting Stage 1 pipeline job with raw_dir=/tmp/test_raw
2025-09-30 12:54:14.949 | INFO     | src.preprocessing.fastp_wrapper:run_fastp:62 - Running fastp: fastp -i /tmp/test_raw/sample_fixed.fastq -o /tmp/test_interim/sample_fixed_clean.fastq.gz -w 4 -j /tmp/test_interim/fastp_report.json -h /tmp/test_interim/fastp_report.html -q 15 -l 50
2025-09-30 12:54:16.426 | INFO     | src.preprocessing.dada2_wrapper:run_dada2:31 - Running DADA2: Rscript scripts/run_dada2.R /tmp/test_interim dada2 /tmp/test_processed single 2 2 pseudo
2025-09-30 12:54:41.949 | INFO     | pipeline:run_pipeline:121 - Metadata written to /tmp/test_processed/stage1_metadata.json
2025-09-30 13:10:28.787 | INFO     | src.pipeline:run_pipeline:44 - Starting Stage 1 pipeline job with raw_dir=data/raw/fastq_dataset
2025-09-30 13:10:28.790 | INFO     | src.preprocessing.fastp_wrapper:run_fastp:62 - Running fastp: fastp -i data/raw/fastq_dataset/anc_R1.fastq -I data/raw/fastq_dataset/anc_R2.fastq -o /tmp/interim/anc_R1_clean.fastq.gz -O /tmp/interim/anc_R2_clean.fastq.gz -w 4 -j /tmp/interim/fastp_report.json -h /tmp/interim/fastp_report.html -q 15 -l 50 --detect_adapter_for_pe
2025-09-30 13:10:50.145 | INFO     | src.preprocessing.dada2_wrapper:run_dada2:31 - Running DADA2: Rscript scripts/run_dada2.R /tmp/interim dada2 /tmp/processed paired 2 2 pseudo
2025-09-30 13:11:12.321 | ERROR    | __main__:<module>:227 - Command '['Rscript', 'scripts/run_dada2.R', '/tmp/interim', 'dada2', '/tmp/processed', 'paired', '2', '2', 'pseudo']' returned non-zero exit status 1.
Traceback (most recent call last):

  File "/usr/lib/python3.12/threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x722d49871d00>
    └ <Thread(ScriptRunner.scriptThread, started 125537905395392)>
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x722d498719e0>
    └ <Thread(ScriptRunner.scriptThread, started 125537905395392)>
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ScriptRunner.scriptThread, started 125537905395392)>
    │    │        │    └ ()
    │    │        └ <Thread(ScriptRunner.scriptThread, started 125537905395392)>
    │    └ <bound method ScriptRunner._run_script_thread of ScriptRunner(_session_id='01807d42-c781-42b2-86ec-9383f22078c6', _main_scrip...
    └ <Thread(ScriptRunner.scriptThread, started 125537905395392)>
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 378, in _run_script_thread
    self._run_script(request.rerun_data)
    │    │           │       └ <property object at 0x722d485d93a0>
    │    │           └ ScriptRequest(type=<ScriptRequestType.RERUN: 'RERUN'>, _rerun_data=RerunData(widget_states=widgets {
    │    │               id: "$$ID-946b940f3cb5...
    │    └ <function ScriptRunner._run_script at 0x722d4869c360>
    └ ScriptRunner(_session_id='01807d42-c781-42b2-86ec-9383f22078c6', _main_script_path='src/web/app.py', _session_state={$$ID-1e2...
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 685, in _run_script
    ) = exec_func_with_error_handling(code_to_exec, ctx)
        │                             │             └ ScriptRunContext(session_id='01807d42-c781-42b2-86ec-9383f22078c6', _enqueue=<bound method ScriptRunner._enqueue_forward_msg ...
        │                             └ <function ScriptRunner._run_script.<locals>.code_to_exec at 0x722d46f61940>
        └ <function exec_func_with_error_handling at 0x722d486484a0>
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
             └ <function ScriptRunner._run_script.<locals>.code_to_exec at 0x722d46f61940>
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
         │     │      └ <member '__dict__' of 'module' objects>
         │     └ <module '__main__' from 'src/web/app.py'>
         └ <code object <module> at 0x722d30052650, file "/home/rishabh/Downloads/SIH-Project/src/web/app.py", line 1>

> File "/home/rishabh/Downloads/SIH-Project/src/web/app.py", line 211, in <module>
    meta = run_pipeline(
           └ <function run_pipeline at 0x722d12612520>

  File "/home/rishabh/Downloads/SIH-Project/src/pipeline.py", line 81, in run_pipeline
    dada2_outputs = run_dada2(
                    └ <function run_dada2 at 0x722d126120c0>

  File "/home/rishabh/Downloads/SIH-Project/src/preprocessing/dada2_wrapper.py", line 32, in run_dada2
    subprocess.run(cmd, check=True)
    │          │   └ ['Rscript', 'scripts/run_dada2.R', '/tmp/interim', 'dada2', '/tmp/processed', 'paired', '2', '2', 'pseudo']
    │          └ <function run at 0x722d49015760>
    └ <module 'subprocess' from '/usr/lib/python3.12/subprocess.py'>

  File "/usr/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
          │                  │        │       └ ['Rscript', 'scripts/run_dada2.R', '/tmp/interim', 'dada2', '/tmp/processed', 'paired', '2', '2', 'pseudo']
          │                  │        └ <Popen: returncode: 1 args: ['Rscript', 'scripts/run_dada2.R', '/tmp/interim...>
          │                  └ 1
          └ <class 'subprocess.CalledProcessError'>

subprocess.CalledProcessError: Command '['Rscript', 'scripts/run_dada2.R', '/tmp/interim', 'dada2', '/tmp/processed', 'paired', '2', '2', 'pseudo']' returned non-zero exit status 1.
2025-09-30 13:54:15.177 | INFO     | src.pipeline:run_pipeline:44 - Starting Stage 1 pipeline job with raw_dir=data/raw/fastq_dataset
2025-09-30 13:54:15.179 | INFO     | src.preprocessing.fastp_wrapper:run_fastp:62 - Running fastp: fastp -i data/raw/fastq_dataset/anc_R1.fastq -I data/raw/fastq_dataset/anc_R2.fastq -o /tmp/interim/anc_R1_clean.fastq.gz -O /tmp/interim/anc_R2_clean.fastq.gz -w 4 -j /tmp/interim/fastp_report.json -h /tmp/interim/fastp_report.html -q 15 -l 50 --detect_adapter_for_pe
2025-09-30 13:54:31.454 | INFO     | src.preprocessing.dada2_wrapper:run_dada2:31 - Running DADA2: Rscript scripts/run_dada2.R /tmp/interim dada2 /tmp/processed paired 2 2 pseudo
2025-09-30 13:54:50.850 | ERROR    | __main__:<module>:227 - Command '['Rscript', 'scripts/run_dada2.R', '/tmp/interim', 'dada2', '/tmp/processed', 'paired', '2', '2', 'pseudo']' returned non-zero exit status 1.
Traceback (most recent call last):

  File "/usr/lib/python3.12/threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7e7638a71d00>
    └ <Thread(ScriptRunner.scriptThread, started 139045362087616)>
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7e7638a719e0>
    └ <Thread(ScriptRunner.scriptThread, started 139045362087616)>
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ScriptRunner.scriptThread, started 139045362087616)>
    │    │        │    └ ()
    │    │        └ <Thread(ScriptRunner.scriptThread, started 139045362087616)>
    │    └ <bound method ScriptRunner._run_script_thread of ScriptRunner(_session_id='5aea8d28-2232-4633-9f96-a8a83194f9b2', _main_scrip...
    └ <Thread(ScriptRunner.scriptThread, started 139045362087616)>
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 378, in _run_script_thread
    self._run_script(request.rerun_data)
    │    │           │       └ <property object at 0x7e763783d350>
    │    │           └ ScriptRequest(type=<ScriptRequestType.RERUN: 'RERUN'>, _rerun_data=RerunData(widget_states=widgets {
    │    │               id: "$$ID-946b940f3cb5...
    │    └ <function ScriptRunner._run_script at 0x7e7637900360>
    └ ScriptRunner(_session_id='5aea8d28-2232-4633-9f96-a8a83194f9b2', _main_script_path='src/web/app.py', _session_state={$$ID-1e2...
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 685, in _run_script
    ) = exec_func_with_error_handling(code_to_exec, ctx)
        │                             │             └ ScriptRunContext(session_id='5aea8d28-2232-4633-9f96-a8a83194f9b2', _enqueue=<bound method ScriptRunner._enqueue_forward_msg ...
        │                             └ <function ScriptRunner._run_script.<locals>.code_to_exec at 0x7e763621e7a0>
        └ <function exec_func_with_error_handling at 0x7e76378a84a0>
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
             └ <function ScriptRunner._run_script.<locals>.code_to_exec at 0x7e763621e7a0>
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
         │     │      └ <member '__dict__' of 'module' objects>
         │     └ <module '__main__' from 'src/web/app.py'>
         └ <code object <module> at 0x7e7620052660, file "/home/rishabh/Downloads/SIH-Project/src/web/app.py", line 1>

> File "/home/rishabh/Downloads/SIH-Project/src/web/app.py", line 211, in <module>
    meta = run_pipeline(
           └ <function run_pipeline at 0x7e76058e32e0>

  File "/home/rishabh/Downloads/SIH-Project/src/pipeline.py", line 81, in run_pipeline
    dada2_outputs = run_dada2(
                    └ <function run_dada2 at 0x7e76058e2e80>

  File "/home/rishabh/Downloads/SIH-Project/src/preprocessing/dada2_wrapper.py", line 32, in run_dada2
    subprocess.run(cmd, check=True)
    │          │   └ ['Rscript', 'scripts/run_dada2.R', '/tmp/interim', 'dada2', '/tmp/processed', 'paired', '2', '2', 'pseudo']
    │          └ <function run at 0x7e7638215760>
    └ <module 'subprocess' from '/usr/lib/python3.12/subprocess.py'>

  File "/usr/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
          │                  │        │       └ ['Rscript', 'scripts/run_dada2.R', '/tmp/interim', 'dada2', '/tmp/processed', 'paired', '2', '2', 'pseudo']
          │                  │        └ <Popen: returncode: 1 args: ['Rscript', 'scripts/run_dada2.R', '/tmp/interim...>
          │                  └ 1
          └ <class 'subprocess.CalledProcessError'>

subprocess.CalledProcessError: Command '['Rscript', 'scripts/run_dada2.R', '/tmp/interim', 'dada2', '/tmp/processed', 'paired', '2', '2', 'pseudo']' returned non-zero exit status 1.
2025-09-30 13:58:32.979 | INFO     | src.pipeline:run_pipeline:44 - Starting Stage 1 pipeline job with raw_dir=data/raw/fastq_dataset
2025-09-30 13:58:32.980 | INFO     | src.preprocessing.fastp_wrapper:run_fastp:62 - Running fastp: fastp -i data/raw/fastq_dataset/anc_R1.fastq -I data/raw/fastq_dataset/anc_R2.fastq -o /tmp/interim/anc_R1_clean.fastq.gz -O /tmp/interim/anc_R2_clean.fastq.gz -w 4 -j /tmp/interim/fastp_report.json -h /tmp/interim/fastp_report.html -q 15 -l 50 --detect_adapter_for_pe
2025-09-30 13:58:48.122 | INFO     | src.preprocessing.dada2_wrapper:run_dada2:31 - Running DADA2: Rscript scripts/run_dada2.R /tmp/interim dada2 /tmp/processed paired 2 2 pseudo
2025-09-30 13:59:05.033 | ERROR    | __main__:<module>:227 - Command '['Rscript', 'scripts/run_dada2.R', '/tmp/interim', 'dada2', '/tmp/processed', 'paired', '2', '2', 'pseudo']' returned non-zero exit status 1.
Traceback (most recent call last):

  File "/usr/lib/python3.12/threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7e7638a71d00>
    └ <Thread(ScriptRunner.scriptThread, started 139045362087616)>
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7e7638a719e0>
    └ <Thread(ScriptRunner.scriptThread, started 139045362087616)>
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ScriptRunner.scriptThread, started 139045362087616)>
    │    │        │    └ ()
    │    │        └ <Thread(ScriptRunner.scriptThread, started 139045362087616)>
    │    └ <bound method ScriptRunner._run_script_thread of ScriptRunner(_session_id='5aea8d28-2232-4633-9f96-a8a83194f9b2', _main_scrip...
    └ <Thread(ScriptRunner.scriptThread, started 139045362087616)>
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 378, in _run_script_thread
    self._run_script(request.rerun_data)
    │    │           │       └ <property object at 0x7e763783d350>
    │    │           └ ScriptRequest(type=<ScriptRequestType.RERUN: 'RERUN'>, _rerun_data=RerunData(widget_states=widgets {
    │    │               id: "$$ID-946b940f3cb5...
    │    └ <function ScriptRunner._run_script at 0x7e7637900360>
    └ ScriptRunner(_session_id='5aea8d28-2232-4633-9f96-a8a83194f9b2', _main_script_path='src/web/app.py', _session_state={$$ID-1e2...
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 685, in _run_script
    ) = exec_func_with_error_handling(code_to_exec, ctx)
        │                             │             └ ScriptRunContext(session_id='5aea8d28-2232-4633-9f96-a8a83194f9b2', _enqueue=<bound method ScriptRunner._enqueue_forward_msg ...
        │                             └ <function ScriptRunner._run_script.<locals>.code_to_exec at 0x7e76363b2520>
        └ <function exec_func_with_error_handling at 0x7e76378a84a0>
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
             └ <function ScriptRunner._run_script.<locals>.code_to_exec at 0x7e76363b2520>
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
         │     │      └ <member '__dict__' of 'module' objects>
         │     └ <module '__main__' from 'src/web/app.py'>
         └ <code object <module> at 0x7e7620052660, file "/home/rishabh/Downloads/SIH-Project/src/web/app.py", line 1>

> File "/home/rishabh/Downloads/SIH-Project/src/web/app.py", line 211, in <module>
    meta = run_pipeline(
           └ <function run_pipeline at 0x7e76058e32e0>

  File "/home/rishabh/Downloads/SIH-Project/src/pipeline.py", line 81, in run_pipeline
    dada2_outputs = run_dada2(
                    └ <function run_dada2 at 0x7e76058e2e80>

  File "/home/rishabh/Downloads/SIH-Project/src/preprocessing/dada2_wrapper.py", line 32, in run_dada2
    subprocess.run(cmd, check=True)
    │          │   └ ['Rscript', 'scripts/run_dada2.R', '/tmp/interim', 'dada2', '/tmp/processed', 'paired', '2', '2', 'pseudo']
    │          └ <function run at 0x7e7638215760>
    └ <module 'subprocess' from '/usr/lib/python3.12/subprocess.py'>

  File "/usr/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
          │                  │        │       └ ['Rscript', 'scripts/run_dada2.R', '/tmp/interim', 'dada2', '/tmp/processed', 'paired', '2', '2', 'pseudo']
          │                  │        └ <Popen: returncode: 1 args: ['Rscript', 'scripts/run_dada2.R', '/tmp/interim...>
          │                  └ 1
          └ <class 'subprocess.CalledProcessError'>

subprocess.CalledProcessError: Command '['Rscript', 'scripts/run_dada2.R', '/tmp/interim', 'dada2', '/tmp/processed', 'paired', '2', '2', 'pseudo']' returned non-zero exit status 1.
2025-09-30 13:59:43.781 | INFO     | src.pipeline:run_pipeline:44 - Starting Stage 1 pipeline job with raw_dir=data/raw/fastq_dataset
2025-09-30 13:59:43.782 | INFO     | src.preprocessing.fastp_wrapper:run_fastp:62 - Running fastp: fastp -i data/raw/fastq_dataset/anc_R1.fastq -I data/raw/fastq_dataset/anc_R2.fastq -o /tmp/interim/anc_R1_clean.fastq.gz -O /tmp/interim/anc_R2_clean.fastq.gz -w 4 -j /tmp/interim/fastp_report.json -h /tmp/interim/fastp_report.html -q 15 -l 50 --detect_adapter_for_pe
2025-09-30 14:00:00.675 | INFO     | src.preprocessing.dada2_wrapper:run_dada2:31 - Running DADA2: Rscript scripts/run_dada2.R /tmp/interim dada2 /tmp/processed paired 2 2 pseudo
2025-09-30 14:00:17.194 | ERROR    | __main__:<module>:227 - Command '['Rscript', 'scripts/run_dada2.R', '/tmp/interim', 'dada2', '/tmp/processed', 'paired', '2', '2', 'pseudo']' returned non-zero exit status 1.
Traceback (most recent call last):

  File "/usr/lib/python3.12/threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7560e0a75d00>
    └ <Thread(ScriptRunner.scriptThread, started 129058086053568)>
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7560e0a759e0>
    └ <Thread(ScriptRunner.scriptThread, started 129058086053568)>
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ScriptRunner.scriptThread, started 129058086053568)>
    │    │        │    └ ()
    │    │        └ <Thread(ScriptRunner.scriptThread, started 129058086053568)>
    │    └ <bound method ScriptRunner._run_script_thread of ScriptRunner(_session_id='b8b2b165-db41-43f1-b49f-b1e576f78f7b', _main_scrip...
    └ <Thread(ScriptRunner.scriptThread, started 129058086053568)>
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 378, in _run_script_thread
    self._run_script(request.rerun_data)
    │    │           │       └ <property object at 0x7560df785300>
    │    │           └ ScriptRequest(type=<ScriptRequestType.RERUN: 'RERUN'>, _rerun_data=RerunData(widget_states=widgets {
    │    │               id: "$$ID-946b940f3cb5...
    │    └ <function ScriptRunner._run_script at 0x7560df848360>
    └ ScriptRunner(_session_id='b8b2b165-db41-43f1-b49f-b1e576f78f7b', _main_script_path='src/web/app.py', _session_state={$$ID-1e2...
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 685, in _run_script
    ) = exec_func_with_error_handling(code_to_exec, ctx)
        │                             │             └ ScriptRunContext(session_id='b8b2b165-db41-43f1-b49f-b1e576f78f7b', _enqueue=<bound method ScriptRunner._enqueue_forward_msg ...
        │                             └ <function ScriptRunner._run_script.<locals>.code_to_exec at 0x7560de1663e0>
        └ <function exec_func_with_error_handling at 0x7560df7f44a0>
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
             └ <function ScriptRunner._run_script.<locals>.code_to_exec at 0x7560de1663e0>
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
         │     │      └ <member '__dict__' of 'module' objects>
         │     └ <module '__main__' from 'src/web/app.py'>
         └ <code object <module> at 0x7560c8052660, file "/home/rishabh/Downloads/SIH-Project/src/web/app.py", line 1>

> File "/home/rishabh/Downloads/SIH-Project/src/web/app.py", line 211, in <module>
    meta = run_pipeline(
           └ <function run_pipeline at 0x7560ad602fc0>

  File "/home/rishabh/Downloads/SIH-Project/src/pipeline.py", line 81, in run_pipeline
    dada2_outputs = run_dada2(
                    └ <function run_dada2 at 0x7560ad602b60>

  File "/home/rishabh/Downloads/SIH-Project/src/preprocessing/dada2_wrapper.py", line 32, in run_dada2
    subprocess.run(cmd, check=True)
    │          │   └ ['Rscript', 'scripts/run_dada2.R', '/tmp/interim', 'dada2', '/tmp/processed', 'paired', '2', '2', 'pseudo']
    │          └ <function run at 0x7560e0219760>
    └ <module 'subprocess' from '/usr/lib/python3.12/subprocess.py'>

  File "/usr/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
          │                  │        │       └ ['Rscript', 'scripts/run_dada2.R', '/tmp/interim', 'dada2', '/tmp/processed', 'paired', '2', '2', 'pseudo']
          │                  │        └ <Popen: returncode: 1 args: ['Rscript', 'scripts/run_dada2.R', '/tmp/interim...>
          │                  └ 1
          └ <class 'subprocess.CalledProcessError'>

subprocess.CalledProcessError: Command '['Rscript', 'scripts/run_dada2.R', '/tmp/interim', 'dada2', '/tmp/processed', 'paired', '2', '2', 'pseudo']' returned non-zero exit status 1.
2025-09-30 14:05:34.501 | INFO     | pipeline:run_pipeline:44 - Starting Stage 1 pipeline job with raw_dir=data/raw/fastq_dataset
2025-09-30 14:05:34.502 | INFO     | src.preprocessing.fastp_wrapper:run_fastp:62 - Running fastp: fastp -i data/raw/fastq_dataset/anc_R1.fastq -I data/raw/fastq_dataset/anc_R2.fastq -o /tmp/interim/anc_R1_clean.fastq.gz -O /tmp/interim/anc_R2_clean.fastq.gz -w 4 -j /tmp/interim/fastp_report.json -h /tmp/interim/fastp_report.html -q 15 -l 50 --detect_adapter_for_pe
2025-09-30 14:05:50.652 | INFO     | src.preprocessing.dada2_wrapper:run_dada2:31 - Running DADA2: Rscript scripts/run_dada2.R /tmp/interim dada2 /tmp/processed paired 2 2 pseudo
2025-09-30 14:48:02.674 | INFO     | pipeline:run_pipeline:121 - Metadata written to /tmp/processed/stage1_metadata.json
2025-09-30 15:17:29.528 | INFO     | src.pipeline:run_pipeline:44 - Starting Stage 1 pipeline job with raw_dir=data/raw/fastq_dataset
2025-09-30 15:17:29.531 | INFO     | src.preprocessing.fastp_wrapper:run_fastp:62 - Running fastp: fastp -i data/raw/fastq_dataset/anc_R1.fastq -I data/raw/fastq_dataset/anc_R2.fastq -o /tmp/interim/anc_R1_clean.fastq.gz -O /tmp/interim/anc_R2_clean.fastq.gz -w 4 -j /tmp/interim/fastp_report.json -h /tmp/interim/fastp_report.html -q 15 -l 50 --detect_adapter_for_pe
2025-09-30 15:17:54.227 | INFO     | src.preprocessing.dada2_wrapper:run_dada2:31 - Running DADA2: Rscript scripts/run_dada2.R /tmp/interim dada2 /tmp/processed paired 2 2 pseudo
2025-09-30 15:55:07.023 | INFO     | src.pipeline:run_pipeline:121 - Metadata written to /tmp/processed/stage1_metadata.json
2025-09-30 17:29:03.216 | INFO     | src.pipeline:run_pipeline:44 - Starting Stage 1 pipeline job with raw_dir=data/raw/fastq_dataset
2025-09-30 17:29:03.218 | INFO     | src.preprocessing.fastp_wrapper:run_fastp:62 - Running fastp: fastp -i data/raw/fastq_dataset/anc_R1.fastq -I data/raw/fastq_dataset/anc_R2.fastq -o /tmp/interim/anc_R1_clean.fastq.gz -O /tmp/interim/anc_R2_clean.fastq.gz -w 4 -j /tmp/interim/fastp_report.json -h /tmp/interim/fastp_report.html -q 15 -l 50 --detect_adapter_for_pe
2025-09-30 17:29:19.843 | INFO     | src.preprocessing.dada2_wrapper:run_dada2:31 - Running DADA2: Rscript scripts/run_dada2.R /tmp/interim dada2 /tmp/processed paired 2 2 pseudo
2025-09-30 17:32:16.217 | INFO     | src.pipeline:run_pipeline:44 - Starting Stage 1 pipeline job with raw_dir=data/raw/fastq_dataset
2025-09-30 17:32:16.219 | INFO     | src.preprocessing.fastp_wrapper:run_fastp:62 - Running fastp: fastp -i data/raw/fastq_dataset/anc_R1.fastq -I data/raw/fastq_dataset/anc_R2.fastq -o /tmp/interim/anc_R1_clean.fastq.gz -O /tmp/interim/anc_R2_clean.fastq.gz -w 4 -j /tmp/interim/fastp_report.json -h /tmp/interim/fastp_report.html -q 15 -l 50 --detect_adapter_for_pe
2025-09-30 17:32:34.010 | INFO     | src.preprocessing.dada2_wrapper:run_dada2:31 - Running DADA2: Rscript scripts/run_dada2.R /tmp/interim dada2 /tmp/processed paired 2 2 pseudo
2025-09-30 18:07:43.837 | INFO     | src.pipeline:run_pipeline:121 - Metadata written to /tmp/processed/stage1_metadata.json
2025-09-30 19:16:37.797 | INFO     | src.pipeline:run_pipeline:44 - Starting Stage 1 pipeline job with raw_dir=/tmp/uploaded_files_0f9ae863
2025-09-30 19:16:37.798 | INFO     | src.preprocessing.fastp_wrapper:run_fastp:62 - Running fastp: fastp -i /tmp/uploaded_files_0f9ae863/sample.fastq -o /tmp/interim/sample_clean.fastq.gz -w 4 -j /tmp/interim/fastp_report.json -h /tmp/interim/fastp_report.html -q 15 -l 50
2025-09-30 19:16:37.804 | ERROR    | __main__:<module>:433 - Command '['fastp', '-i', '/tmp/uploaded_files_0f9ae863/sample.fastq', '-o', '/tmp/interim/sample_clean.fastq.gz', '-w', '4', '-j', '/tmp/interim/fastp_report.json', '-h', '/tmp/interim/fastp_report.html', '-q', '15', '-l', '50']' returned non-zero exit status 255.
Traceback (most recent call last):

  File "/usr/lib/python3.12/threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x743116271d00>
    └ <Thread(ScriptRunner.scriptThread, started 127752862693056)>
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7431162719e0>
    └ <Thread(ScriptRunner.scriptThread, started 127752862693056)>
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ScriptRunner.scriptThread, started 127752862693056)>
    │    │        │    └ ()
    │    │        └ <Thread(ScriptRunner.scriptThread, started 127752862693056)>
    │    └ <bound method ScriptRunner._run_script_thread of ScriptRunner(_session_id='8ef0672f-0751-4127-8384-786d1ae78ee9', _main_scrip...
    └ <Thread(ScriptRunner.scriptThread, started 127752862693056)>
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 378, in _run_script_thread
    self._run_script(request.rerun_data)
    │    │           │       └ <property object at 0x743115074f90>
    │    │           └ ScriptRequest(type=<ScriptRequestType.RERUN: 'RERUN'>, _rerun_data=RerunData(widget_states=widgets {
    │    │               id: "$$ID-1e2cc8597619...
    │    └ <function ScriptRunner._run_script at 0x743115138360>
    └ ScriptRunner(_session_id='8ef0672f-0751-4127-8384-786d1ae78ee9', _main_script_path='src/web/app.py', _session_state={$$STREAM...
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 685, in _run_script
    ) = exec_func_with_error_handling(code_to_exec, ctx)
        │                             │             └ ScriptRunContext(session_id='8ef0672f-0751-4127-8384-786d1ae78ee9', _enqueue=<bound method ScriptRunner._enqueue_forward_msg ...
        │                             └ <function ScriptRunner._run_script.<locals>.code_to_exec at 0x7430def499e0>
        └ <function exec_func_with_error_handling at 0x7431150e04a0>
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
             └ <function ScriptRunner._run_script.<locals>.code_to_exec at 0x7430def499e0>
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
         │     │      └ <member '__dict__' of 'module' objects>
         │     └ <module '__main__' from 'src/web/app.py'>
         └ <code object <module> at 0x7430fc05ddb0, file "/home/rishabh/Downloads/SIH-Project/src/web/app.py", line 1>

> File "/home/rishabh/Downloads/SIH-Project/src/web/app.py", line 415, in <module>
    meta = run_pipeline(
           └ <function run_pipeline at 0x7430df16b1a0>

  File "/home/rishabh/Downloads/SIH-Project/src/pipeline.py", line 64, in run_pipeline
    fastp_outputs = run_fastp(
                    └ <function run_fastp at 0x7430df16ac00>

  File "/home/rishabh/Downloads/SIH-Project/src/preprocessing/fastp_wrapper.py", line 63, in run_fastp
    subprocess.run(cmd, check=True)
    │          │   └ ['fastp', '-i', '/tmp/uploaded_files_0f9ae863/sample.fastq', '-o', '/tmp/interim/sample_clean.fastq.gz', '-w', '4', '-j', '/t...
    │          └ <function run at 0x743115a15760>
    └ <module 'subprocess' from '/usr/lib/python3.12/subprocess.py'>

  File "/usr/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
          │                  │        │       └ ['fastp', '-i', '/tmp/uploaded_files_0f9ae863/sample.fastq', '-o', '/tmp/interim/sample_clean.fastq.gz', '-w', '4', '-j', '/t...
          │                  │        └ <Popen: returncode: 255 args: ['fastp', '-i', '/tmp/uploaded_files_0f9ae863/...>
          │                  └ 255
          └ <class 'subprocess.CalledProcessError'>

subprocess.CalledProcessError: Command '['fastp', '-i', '/tmp/uploaded_files_0f9ae863/sample.fastq', '-o', '/tmp/interim/sample_clean.fastq.gz', '-w', '4', '-j', '/tmp/interim/fastp_report.json', '-h', '/tmp/interim/fastp_report.html', '-q', '15', '-l', '50']' returned non-zero exit status 255.
2025-09-30 19:30:18.747 | INFO     | src.pipeline:run_pipeline:44 - Starting Stage 1 pipeline job with raw_dir=/tmp/uploaded_files_ca70c768
2025-09-30 19:30:18.749 | INFO     | src.preprocessing.fastp_wrapper:run_fastp:62 - Running fastp: fastp -i /tmp/uploaded_files_ca70c768/sample.fastq -o /tmp/interim/sample_clean.fastq.gz -w 4 -j /tmp/interim/fastp_report.json -h /tmp/interim/fastp_report.html -q 15 -l 50
2025-09-30 19:30:18.754 | ERROR    | __main__:<module>:433 - Command '['fastp', '-i', '/tmp/uploaded_files_ca70c768/sample.fastq', '-o', '/tmp/interim/sample_clean.fastq.gz', '-w', '4', '-j', '/tmp/interim/fastp_report.json', '-h', '/tmp/interim/fastp_report.html', '-q', '15', '-l', '50']' returned non-zero exit status 255.
Traceback (most recent call last):

  File "/usr/lib/python3.12/threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x755856571d00>
    └ <Thread(ScriptRunner.scriptThread, started 129021339207360)>
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7558565719e0>
    └ <Thread(ScriptRunner.scriptThread, started 129021339207360)>
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ScriptRunner.scriptThread, started 129021339207360)>
    │    │        │    └ ()
    │    │        └ <Thread(ScriptRunner.scriptThread, started 129021339207360)>
    │    └ <bound method ScriptRunner._run_script_thread of ScriptRunner(_session_id='42a73af9-7c25-4ae8-9d5b-a3e1bc72c966', _main_scrip...
    └ <Thread(ScriptRunner.scriptThread, started 129021339207360)>
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 378, in _run_script_thread
    self._run_script(request.rerun_data)
    │    │           │       └ <property object at 0x75585533d350>
    │    │           └ ScriptRequest(type=<ScriptRequestType.RERUN: 'RERUN'>, _rerun_data=RerunData(widget_states=widgets {
    │    │               id: "$$ID-946b940f3cb5...
    │    └ <function ScriptRunner._run_script at 0x755855400360>
    └ ScriptRunner(_session_id='42a73af9-7c25-4ae8-9d5b-a3e1bc72c966', _main_script_path='src/web/app.py', _session_state={$$ID-1e2...
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 685, in _run_script
    ) = exec_func_with_error_handling(code_to_exec, ctx)
        │                             │             └ ScriptRunContext(session_id='42a73af9-7c25-4ae8-9d5b-a3e1bc72c966', _enqueue=<bound method ScriptRunner._enqueue_forward_msg ...
        │                             └ <function ScriptRunner._run_script.<locals>.code_to_exec at 0x75581f1b6480>
        └ <function exec_func_with_error_handling at 0x7558553a84a0>
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
             └ <function ScriptRunner._run_script.<locals>.code_to_exec at 0x75581f1b6480>
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
         │     │      └ <member '__dict__' of 'module' objects>
         │     └ <module '__main__' from 'src/web/app.py'>
         └ <code object <module> at 0x75583c05ddb0, file "/home/rishabh/Downloads/SIH-Project/src/web/app.py", line 1>

> File "/home/rishabh/Downloads/SIH-Project/src/web/app.py", line 415, in <module>
    meta = run_pipeline(
           └ <function run_pipeline at 0x75581f17f7e0>

  File "/home/rishabh/Downloads/SIH-Project/src/pipeline.py", line 64, in run_pipeline
    fastp_outputs = run_fastp(
                    └ <function run_fastp at 0x75581f17f240>

  File "/home/rishabh/Downloads/SIH-Project/src/preprocessing/fastp_wrapper.py", line 63, in run_fastp
    subprocess.run(cmd, check=True)
    │          │   └ ['fastp', '-i', '/tmp/uploaded_files_ca70c768/sample.fastq', '-o', '/tmp/interim/sample_clean.fastq.gz', '-w', '4', '-j', '/t...
    │          └ <function run at 0x755855d15760>
    └ <module 'subprocess' from '/usr/lib/python3.12/subprocess.py'>

  File "/usr/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
          │                  │        │       └ ['fastp', '-i', '/tmp/uploaded_files_ca70c768/sample.fastq', '-o', '/tmp/interim/sample_clean.fastq.gz', '-w', '4', '-j', '/t...
          │                  │        └ <Popen: returncode: 255 args: ['fastp', '-i', '/tmp/uploaded_files_ca70c768/...>
          │                  └ 255
          └ <class 'subprocess.CalledProcessError'>

subprocess.CalledProcessError: Command '['fastp', '-i', '/tmp/uploaded_files_ca70c768/sample.fastq', '-o', '/tmp/interim/sample_clean.fastq.gz', '-w', '4', '-j', '/tmp/interim/fastp_report.json', '-h', '/tmp/interim/fastp_report.html', '-q', '15', '-l', '50']' returned non-zero exit status 255.
2025-09-30 19:38:24.869 | INFO     | src.pipeline:run_pipeline:44 - Starting Stage 1 pipeline job with raw_dir=/tmp/uploaded_files_35e8a5f6
2025-09-30 19:38:24.871 | INFO     | src.preprocessing.fastp_wrapper:run_fastp:62 - Running fastp: fastp -i /tmp/uploaded_files_35e8a5f6/sample.fastq -o /tmp/interim/sample_clean.fastq.gz -w 4 -j /tmp/interim/fastp_report.json -h /tmp/interim/fastp_report.html -q 15 -l 50
2025-09-30 19:38:24.877 | ERROR    | __main__:<module>:433 - Command '['fastp', '-i', '/tmp/uploaded_files_35e8a5f6/sample.fastq', '-o', '/tmp/interim/sample_clean.fastq.gz', '-w', '4', '-j', '/tmp/interim/fastp_report.json', '-h', '/tmp/interim/fastp_report.html', '-q', '15', '-l', '50']' returned non-zero exit status 255.
Traceback (most recent call last):

  File "/usr/lib/python3.12/threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f344dc75d00>
    └ <Thread(ScriptRunner.scriptThread, started 139861693556416)>
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f344dc759e0>
    └ <Thread(ScriptRunner.scriptThread, started 139861693556416)>
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ScriptRunner.scriptThread, started 139861693556416)>
    │    │        │    └ ()
    │    │        └ <Thread(ScriptRunner.scriptThread, started 139861693556416)>
    │    └ <bound method ScriptRunner._run_script_thread of ScriptRunner(_session_id='8dae1ca1-69eb-41f2-a397-2883bac48ca4', _main_scrip...
    └ <Thread(ScriptRunner.scriptThread, started 139861693556416)>
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 378, in _run_script_thread
    self._run_script(request.rerun_data)
    │    │           │       └ <property object at 0x7f344ca79350>
    │    │           └ ScriptRequest(type=<ScriptRequestType.RERUN: 'RERUN'>, _rerun_data=RerunData(widget_states=widgets {
    │    │               id: "$$ID-946b940f3cb5...
    │    └ <function ScriptRunner._run_script at 0x7f344cb3c360>
    └ ScriptRunner(_session_id='8dae1ca1-69eb-41f2-a397-2883bac48ca4', _main_script_path='src/web/app.py', _session_state={$$ID-1e2...
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 685, in _run_script
    ) = exec_func_with_error_handling(code_to_exec, ctx)
        │                             │             └ ScriptRunContext(session_id='8dae1ca1-69eb-41f2-a397-2883bac48ca4', _enqueue=<bound method ScriptRunner._enqueue_forward_msg ...
        │                             └ <function ScriptRunner._run_script.<locals>.code_to_exec at 0x7f3416925e40>
        └ <function exec_func_with_error_handling at 0x7f344cae84a0>
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
             └ <function ScriptRunner._run_script.<locals>.code_to_exec at 0x7f3416925e40>
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
         │     │      └ <member '__dict__' of 'module' objects>
         │     └ <module '__main__' from 'src/web/app.py'>
         └ <code object <module> at 0x7f343405ddb0, file "/home/rishabh/Downloads/SIH-Project/src/web/app.py", line 1>

> File "/home/rishabh/Downloads/SIH-Project/src/web/app.py", line 415, in <module>
    meta = run_pipeline(
           └ <function run_pipeline at 0x7f3416b47240>

  File "/home/rishabh/Downloads/SIH-Project/src/pipeline.py", line 64, in run_pipeline
    fastp_outputs = run_fastp(
                    └ <function run_fastp at 0x7f3416b46ca0>

  File "/home/rishabh/Downloads/SIH-Project/src/preprocessing/fastp_wrapper.py", line 63, in run_fastp
    subprocess.run(cmd, check=True)
    │          │   └ ['fastp', '-i', '/tmp/uploaded_files_35e8a5f6/sample.fastq', '-o', '/tmp/interim/sample_clean.fastq.gz', '-w', '4', '-j', '/t...
    │          └ <function run at 0x7f344d419760>
    └ <module 'subprocess' from '/usr/lib/python3.12/subprocess.py'>

  File "/usr/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
          │                  │        │       └ ['fastp', '-i', '/tmp/uploaded_files_35e8a5f6/sample.fastq', '-o', '/tmp/interim/sample_clean.fastq.gz', '-w', '4', '-j', '/t...
          │                  │        └ <Popen: returncode: 255 args: ['fastp', '-i', '/tmp/uploaded_files_35e8a5f6/...>
          │                  └ 255
          └ <class 'subprocess.CalledProcessError'>

subprocess.CalledProcessError: Command '['fastp', '-i', '/tmp/uploaded_files_35e8a5f6/sample.fastq', '-o', '/tmp/interim/sample_clean.fastq.gz', '-w', '4', '-j', '/tmp/interim/fastp_report.json', '-h', '/tmp/interim/fastp_report.html', '-q', '15', '-l', '50']' returned non-zero exit status 255.
2025-09-30 19:39:30.124 | INFO     | src.pipeline:run_pipeline:44 - Starting Stage 1 pipeline job with raw_dir=/tmp/uploaded_files_f2675f06
2025-09-30 19:39:30.127 | INFO     | src.preprocessing.fastp_wrapper:run_fastp:62 - Running fastp: fastp -i /tmp/uploaded_files_f2675f06/sample.fastq -o /tmp/interim/sample_clean.fastq.gz -w 4 -j /tmp/interim/fastp_report.json -h /tmp/interim/fastp_report.html -q 15 -l 50
2025-09-30 19:39:30.134 | ERROR    | __main__:<module>:433 - Command '['fastp', '-i', '/tmp/uploaded_files_f2675f06/sample.fastq', '-o', '/tmp/interim/sample_clean.fastq.gz', '-w', '4', '-j', '/tmp/interim/fastp_report.json', '-h', '/tmp/interim/fastp_report.html', '-q', '15', '-l', '50']' returned non-zero exit status 255.
Traceback (most recent call last):

  File "/usr/lib/python3.12/threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f344dc75d00>
    └ <Thread(ScriptRunner.scriptThread, started 139861305583296)>
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f344dc759e0>
    └ <Thread(ScriptRunner.scriptThread, started 139861305583296)>
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ScriptRunner.scriptThread, started 139861305583296)>
    │    │        │    └ ()
    │    │        └ <Thread(ScriptRunner.scriptThread, started 139861305583296)>
    │    └ <bound method ScriptRunner._run_script_thread of ScriptRunner(_session_id='8dae1ca1-69eb-41f2-a397-2883bac48ca4', _main_scrip...
    └ <Thread(ScriptRunner.scriptThread, started 139861305583296)>
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 378, in _run_script_thread
    self._run_script(request.rerun_data)
    │    │           │       └ <property object at 0x7f344ca79350>
    │    │           └ ScriptRequest(type=<ScriptRequestType.RERUN: 'RERUN'>, _rerun_data=RerunData(widget_states=widgets {
    │    │               id: "$$ID-946b940f3cb5...
    │    └ <function ScriptRunner._run_script at 0x7f344cb3c360>
    └ ScriptRunner(_session_id='8dae1ca1-69eb-41f2-a397-2883bac48ca4', _main_script_path='src/web/app.py', _session_state={$$ID-1e2...
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 685, in _run_script
    ) = exec_func_with_error_handling(code_to_exec, ctx)
        │                             │             └ ScriptRunContext(session_id='8dae1ca1-69eb-41f2-a397-2883bac48ca4', _enqueue=<bound method ScriptRunner._enqueue_forward_msg ...
        │                             └ <function ScriptRunner._run_script.<locals>.code_to_exec at 0x7f344b5edee0>
        └ <function exec_func_with_error_handling at 0x7f344cae84a0>
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
             └ <function ScriptRunner._run_script.<locals>.code_to_exec at 0x7f344b5edee0>
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
         │     │      └ <member '__dict__' of 'module' objects>
         │     └ <module '__main__' from 'src/web/app.py'>
         └ <code object <module> at 0x7f343405ddb0, file "/home/rishabh/Downloads/SIH-Project/src/web/app.py", line 1>

> File "/home/rishabh/Downloads/SIH-Project/src/web/app.py", line 415, in <module>
    meta = run_pipeline(
           └ <function run_pipeline at 0x7f3416b47240>

  File "/home/rishabh/Downloads/SIH-Project/src/pipeline.py", line 64, in run_pipeline
    fastp_outputs = run_fastp(
                    └ <function run_fastp at 0x7f3416b46ca0>

  File "/home/rishabh/Downloads/SIH-Project/src/preprocessing/fastp_wrapper.py", line 63, in run_fastp
    subprocess.run(cmd, check=True)
    │          │   └ ['fastp', '-i', '/tmp/uploaded_files_f2675f06/sample.fastq', '-o', '/tmp/interim/sample_clean.fastq.gz', '-w', '4', '-j', '/t...
    │          └ <function run at 0x7f344d419760>
    └ <module 'subprocess' from '/usr/lib/python3.12/subprocess.py'>

  File "/usr/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
          │                  │        │       └ ['fastp', '-i', '/tmp/uploaded_files_f2675f06/sample.fastq', '-o', '/tmp/interim/sample_clean.fastq.gz', '-w', '4', '-j', '/t...
          │                  │        └ <Popen: returncode: 255 args: ['fastp', '-i', '/tmp/uploaded_files_f2675f06/...>
          │                  └ 255
          └ <class 'subprocess.CalledProcessError'>

subprocess.CalledProcessError: Command '['fastp', '-i', '/tmp/uploaded_files_f2675f06/sample.fastq', '-o', '/tmp/interim/sample_clean.fastq.gz', '-w', '4', '-j', '/tmp/interim/fastp_report.json', '-h', '/tmp/interim/fastp_report.html', '-q', '15', '-l', '50']' returned non-zero exit status 255.
2025-09-30 19:59:57.861 | INFO     | src.pipeline:run_pipeline:44 - Starting Stage 1 pipeline job with raw_dir=/tmp/uploaded_files_12d63e0c
2025-09-30 19:59:57.862 | INFO     | src.preprocessing.fastp_wrapper:run_fastp:62 - Running fastp: fastp -i /tmp/uploaded_files_12d63e0c/sample.fastq -o /tmp/interim/sample_clean.fastq.gz -w 4 -j /tmp/interim/fastp_report.json -h /tmp/interim/fastp_report.html -q 15 -l 50
2025-09-30 19:59:57.870 | ERROR    | __main__:<module>:433 - Command '['fastp', '-i', '/tmp/uploaded_files_12d63e0c/sample.fastq', '-o', '/tmp/interim/sample_clean.fastq.gz', '-w', '4', '-j', '/tmp/interim/fastp_report.json', '-h', '/tmp/interim/fastp_report.html', '-q', '15', '-l', '50']' returned non-zero exit status 255.
Traceback (most recent call last):

  File "/usr/lib/python3.12/threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7b71be871d00>
    └ <Thread(ScriptRunner.scriptThread, started 135727531681472)>
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7b71be8719e0>
    └ <Thread(ScriptRunner.scriptThread, started 135727531681472)>
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ScriptRunner.scriptThread, started 135727531681472)>
    │    │        │    └ ()
    │    │        └ <Thread(ScriptRunner.scriptThread, started 135727531681472)>
    │    └ <bound method ScriptRunner._run_script_thread of ScriptRunner(_session_id='d3c160fa-b4c2-4215-a6f2-be34d6a897eb', _main_scrip...
    └ <Thread(ScriptRunner.scriptThread, started 135727531681472)>
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 378, in _run_script_thread
    self._run_script(request.rerun_data)
    │    │           │       └ <property object at 0x7b71bd675350>
    │    │           └ ScriptRequest(type=<ScriptRequestType.RERUN: 'RERUN'>, _rerun_data=RerunData(widget_states=widgets {
    │    │               id: "$$ID-946b940f3cb5...
    │    └ <function ScriptRunner._run_script at 0x7b71bd734360>
    └ ScriptRunner(_session_id='d3c160fa-b4c2-4215-a6f2-be34d6a897eb', _main_script_path='src/web/app.py', _session_state={$$ID-946...
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 685, in _run_script
    ) = exec_func_with_error_handling(code_to_exec, ctx)
        │                             │             └ ScriptRunContext(session_id='d3c160fa-b4c2-4215-a6f2-be34d6a897eb', _enqueue=<bound method ScriptRunner._enqueue_forward_msg ...
        │                             └ <function ScriptRunner._run_script.<locals>.code_to_exec at 0x7b71bc08a5c0>
        └ <function exec_func_with_error_handling at 0x7b71bd6e04a0>
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
             └ <function ScriptRunner._run_script.<locals>.code_to_exec at 0x7b71bc08a5c0>
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
         │     │      └ <member '__dict__' of 'module' objects>
         │     └ <module '__main__' from 'src/web/app.py'>
         └ <code object <module> at 0x7b71a405ddb0, file "/home/rishabh/Downloads/SIH-Project/src/web/app.py", line 1>

> File "/home/rishabh/Downloads/SIH-Project/src/web/app.py", line 415, in <module>
    meta = run_pipeline(
           └ <function run_pipeline at 0x7b7187747240>

  File "/home/rishabh/Downloads/SIH-Project/src/pipeline.py", line 64, in run_pipeline
    fastp_outputs = run_fastp(
                    └ <function run_fastp at 0x7b7187746ca0>

  File "/home/rishabh/Downloads/SIH-Project/src/preprocessing/fastp_wrapper.py", line 63, in run_fastp
    subprocess.run(cmd, check=True)
    │          │   └ ['fastp', '-i', '/tmp/uploaded_files_12d63e0c/sample.fastq', '-o', '/tmp/interim/sample_clean.fastq.gz', '-w', '4', '-j', '/t...
    │          └ <function run at 0x7b71be015760>
    └ <module 'subprocess' from '/usr/lib/python3.12/subprocess.py'>

  File "/usr/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
          │                  │        │       └ ['fastp', '-i', '/tmp/uploaded_files_12d63e0c/sample.fastq', '-o', '/tmp/interim/sample_clean.fastq.gz', '-w', '4', '-j', '/t...
          │                  │        └ <Popen: returncode: 255 args: ['fastp', '-i', '/tmp/uploaded_files_12d63e0c/...>
          │                  └ 255
          └ <class 'subprocess.CalledProcessError'>

subprocess.CalledProcessError: Command '['fastp', '-i', '/tmp/uploaded_files_12d63e0c/sample.fastq', '-o', '/tmp/interim/sample_clean.fastq.gz', '-w', '4', '-j', '/tmp/interim/fastp_report.json', '-h', '/tmp/interim/fastp_report.html', '-q', '15', '-l', '50']' returned non-zero exit status 255.
2025-09-30 20:03:20.020 | INFO     | src.pipeline:run_pipeline:44 - Starting Stage 1 pipeline job with raw_dir=/tmp/uploaded_files_45be8ed9
2025-09-30 20:03:20.022 | INFO     | src.preprocessing.fastp_wrapper:run_fastp:62 - Running fastp: fastp -i /tmp/uploaded_files_45be8ed9/sample.fastq -o /tmp/interim/sample_clean.fastq.gz -w 4 -j /tmp/interim/fastp_report.json -h /tmp/interim/fastp_report.html -q 15 -l 50
2025-09-30 20:03:20.028 | ERROR    | __main__:<module>:433 - Command '['fastp', '-i', '/tmp/uploaded_files_45be8ed9/sample.fastq', '-o', '/tmp/interim/sample_clean.fastq.gz', '-w', '4', '-j', '/tmp/interim/fastp_report.json', '-h', '/tmp/interim/fastp_report.html', '-q', '15', '-l', '50']' returned non-zero exit status 255.
Traceback (most recent call last):

  File "/usr/lib/python3.12/threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7cc5ef371d00>
    └ <Thread(ScriptRunner.scriptThread, started 137188636358336)>
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7cc5ef3719e0>
    └ <Thread(ScriptRunner.scriptThread, started 137188636358336)>
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ScriptRunner.scriptThread, started 137188636358336)>
    │    │        │    └ ()
    │    │        └ <Thread(ScriptRunner.scriptThread, started 137188636358336)>
    │    └ <bound method ScriptRunner._run_script_thread of ScriptRunner(_session_id='a4fa28d2-a06f-4f28-be78-1fd556d3864f', _main_scrip...
    └ <Thread(ScriptRunner.scriptThread, started 137188636358336)>
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 378, in _run_script_thread
    self._run_script(request.rerun_data)
    │    │           │       └ <property object at 0x7cc5ee13d350>
    │    │           └ ScriptRequest(type=<ScriptRequestType.RERUN: 'RERUN'>, _rerun_data=RerunData(widget_states=widgets {
    │    │               id: "$$ID-946b940f3cb5...
    │    └ <function ScriptRunner._run_script at 0x7cc5ee200360>
    └ ScriptRunner(_session_id='a4fa28d2-a06f-4f28-be78-1fd556d3864f', _main_script_path='src/web/app.py', _session_state={$$ID-946...
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 685, in _run_script
    ) = exec_func_with_error_handling(code_to_exec, ctx)
        │                             │             └ ScriptRunContext(session_id='a4fa28d2-a06f-4f28-be78-1fd556d3864f', _enqueue=<bound method ScriptRunner._enqueue_forward_msg ...
        │                             └ <function ScriptRunner._run_script.<locals>.code_to_exec at 0x7cc5b7ffd620>
        └ <function exec_func_with_error_handling at 0x7cc5ee1a84a0>
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
             └ <function ScriptRunner._run_script.<locals>.code_to_exec at 0x7cc5b7ffd620>
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
         │     │      └ <member '__dict__' of 'module' objects>
         │     └ <module '__main__' from 'src/web/app.py'>
         └ <code object <module> at 0x7cc5dc05ddb0, file "/home/rishabh/Downloads/SIH-Project/src/web/app.py", line 1>

> File "/home/rishabh/Downloads/SIH-Project/src/web/app.py", line 415, in <module>
    meta = run_pipeline(
           └ <function run_pipeline at 0x7cc5bc1ebba0>

  File "/home/rishabh/Downloads/SIH-Project/src/pipeline.py", line 64, in run_pipeline
    fastp_outputs = run_fastp(
                    └ <function run_fastp at 0x7cc5bc1eb600>

  File "/home/rishabh/Downloads/SIH-Project/src/preprocessing/fastp_wrapper.py", line 63, in run_fastp
    subprocess.run(cmd, check=True)
    │          │   └ ['fastp', '-i', '/tmp/uploaded_files_45be8ed9/sample.fastq', '-o', '/tmp/interim/sample_clean.fastq.gz', '-w', '4', '-j', '/t...
    │          └ <function run at 0x7cc5eeb15760>
    └ <module 'subprocess' from '/usr/lib/python3.12/subprocess.py'>

  File "/usr/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
          │                  │        │       └ ['fastp', '-i', '/tmp/uploaded_files_45be8ed9/sample.fastq', '-o', '/tmp/interim/sample_clean.fastq.gz', '-w', '4', '-j', '/t...
          │                  │        └ <Popen: returncode: 255 args: ['fastp', '-i', '/tmp/uploaded_files_45be8ed9/...>
          │                  └ 255
          └ <class 'subprocess.CalledProcessError'>

subprocess.CalledProcessError: Command '['fastp', '-i', '/tmp/uploaded_files_45be8ed9/sample.fastq', '-o', '/tmp/interim/sample_clean.fastq.gz', '-w', '4', '-j', '/tmp/interim/fastp_report.json', '-h', '/tmp/interim/fastp_report.html', '-q', '15', '-l', '50']' returned non-zero exit status 255.
2025-09-30 20:14:32.339 | INFO     | src.pipeline:run_pipeline:44 - Starting Stage 1 pipeline job with raw_dir=/tmp/uploaded_files_61b52d0b
2025-09-30 20:14:32.341 | INFO     | src.preprocessing.fastp_wrapper:run_fastp:62 - Running fastp: fastp -i /tmp/uploaded_files_61b52d0b/sample.fastq -o /tmp/interim/sample_clean.fastq.gz -w 4 -j /tmp/interim/fastp_report.json -h /tmp/interim/fastp_report.html -q 15 -l 50
2025-09-30 20:14:32.347 | ERROR    | __main__:<module>:433 - Command '['fastp', '-i', '/tmp/uploaded_files_61b52d0b/sample.fastq', '-o', '/tmp/interim/sample_clean.fastq.gz', '-w', '4', '-j', '/tmp/interim/fastp_report.json', '-h', '/tmp/interim/fastp_report.html', '-q', '15', '-l', '50']' returned non-zero exit status 255.
Traceback (most recent call last):

  File "/usr/lib/python3.12/threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x73a7c3475d00>
    └ <Thread(ScriptRunner.scriptThread, started 127163403577024)>
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x73a7c34759e0>
    └ <Thread(ScriptRunner.scriptThread, started 127163403577024)>
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ScriptRunner.scriptThread, started 127163403577024)>
    │    │        │    └ ()
    │    │        └ <Thread(ScriptRunner.scriptThread, started 127163403577024)>
    │    └ <bound method ScriptRunner._run_script_thread of ScriptRunner(_session_id='8666602b-97c5-402c-bc31-de93c3eee931', _main_scrip...
    └ <Thread(ScriptRunner.scriptThread, started 127163403577024)>
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 378, in _run_script_thread
    self._run_script(request.rerun_data)
    │    │           │       └ <property object at 0x73a7c2279350>
    │    │           └ ScriptRequest(type=<ScriptRequestType.RERUN: 'RERUN'>, _rerun_data=RerunData(widget_states=widgets {
    │    │               id: "$$ID-1e2cc8597619...
    │    └ <function ScriptRunner._run_script at 0x73a7c233c360>
    └ ScriptRunner(_session_id='8666602b-97c5-402c-bc31-de93c3eee931', _main_script_path='src/web/app.py', _session_state={$$ID-1e2...
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 685, in _run_script
    ) = exec_func_with_error_handling(code_to_exec, ctx)
        │                             │             └ ScriptRunContext(session_id='8666602b-97c5-402c-bc31-de93c3eee931', _enqueue=<bound method ScriptRunner._enqueue_forward_msg ...
        │                             └ <function ScriptRunner._run_script.<locals>.code_to_exec at 0x73a7c0c5a7a0>
        └ <function exec_func_with_error_handling at 0x73a7c22e84a0>
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
             └ <function ScriptRunner._run_script.<locals>.code_to_exec at 0x73a7c0c5a7a0>
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
         │     │      └ <member '__dict__' of 'module' objects>
         │     └ <module '__main__' from 'src/web/app.py'>
         └ <code object <module> at 0x73a7b005ddb0, file "/home/rishabh/Downloads/SIH-Project/src/web/app.py", line 1>

> File "/home/rishabh/Downloads/SIH-Project/src/web/app.py", line 415, in <module>
    meta = run_pipeline(
           └ <function run_pipeline at 0x73a790123600>

  File "/home/rishabh/Downloads/SIH-Project/src/pipeline.py", line 64, in run_pipeline
    fastp_outputs = run_fastp(
                    └ <function run_fastp at 0x73a790123060>

  File "/home/rishabh/Downloads/SIH-Project/src/preprocessing/fastp_wrapper.py", line 63, in run_fastp
    subprocess.run(cmd, check=True)
    │          │   └ ['fastp', '-i', '/tmp/uploaded_files_61b52d0b/sample.fastq', '-o', '/tmp/interim/sample_clean.fastq.gz', '-w', '4', '-j', '/t...
    │          └ <function run at 0x73a7c2c19760>
    └ <module 'subprocess' from '/usr/lib/python3.12/subprocess.py'>

  File "/usr/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
          │                  │        │       └ ['fastp', '-i', '/tmp/uploaded_files_61b52d0b/sample.fastq', '-o', '/tmp/interim/sample_clean.fastq.gz', '-w', '4', '-j', '/t...
          │                  │        └ <Popen: returncode: 255 args: ['fastp', '-i', '/tmp/uploaded_files_61b52d0b/...>
          │                  └ 255
          └ <class 'subprocess.CalledProcessError'>

subprocess.CalledProcessError: Command '['fastp', '-i', '/tmp/uploaded_files_61b52d0b/sample.fastq', '-o', '/tmp/interim/sample_clean.fastq.gz', '-w', '4', '-j', '/tmp/interim/fastp_report.json', '-h', '/tmp/interim/fastp_report.html', '-q', '15', '-l', '50']' returned non-zero exit status 255.
2025-09-30 20:20:01.472 | INFO     | src.pipeline:run_pipeline:44 - Starting Stage 1 pipeline job with raw_dir=/tmp/uploaded_files_119077e7
2025-09-30 20:20:01.475 | INFO     | src.preprocessing.fastp_wrapper:run_fastp:62 - Running fastp: fastp -i /tmp/uploaded_files_119077e7/sample.fastq -o /tmp/interim/sample_clean.fastq.gz -w 4 -j /tmp/interim/fastp_report.json -h /tmp/interim/fastp_report.html -q 15 -l 50
2025-09-30 20:20:01.480 | ERROR    | __main__:<module>:433 - Command '['fastp', '-i', '/tmp/uploaded_files_119077e7/sample.fastq', '-o', '/tmp/interim/sample_clean.fastq.gz', '-w', '4', '-j', '/tmp/interim/fastp_report.json', '-h', '/tmp/interim/fastp_report.html', '-q', '15', '-l', '50']' returned non-zero exit status 255.
Traceback (most recent call last):

  File "/usr/lib/python3.12/threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7330aba75d00>
    └ <Thread(ScriptRunner.scriptThread, started 126651941779136)>
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7330aba759e0>
    └ <Thread(ScriptRunner.scriptThread, started 126651941779136)>
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ScriptRunner.scriptThread, started 126651941779136)>
    │    │        │    └ ()
    │    │        └ <Thread(ScriptRunner.scriptThread, started 126651941779136)>
    │    └ <bound method ScriptRunner._run_script_thread of ScriptRunner(_session_id='06b85b09-d57a-4c30-9062-de6ae8fda417', _main_scrip...
    └ <Thread(ScriptRunner.scriptThread, started 126651941779136)>
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 378, in _run_script_thread
    self._run_script(request.rerun_data)
    │    │           │       └ <property object at 0x7330aa879350>
    │    │           └ ScriptRequest(type=<ScriptRequestType.RERUN: 'RERUN'>, _rerun_data=RerunData(widget_states=widgets {
    │    │               id: "$$ID-1e2cc8597619...
    │    └ <function ScriptRunner._run_script at 0x7330aa93c360>
    └ ScriptRunner(_session_id='06b85b09-d57a-4c30-9062-de6ae8fda417', _main_script_path='src/web/app.py', _session_state={$$ID-1e2...
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 685, in _run_script
    ) = exec_func_with_error_handling(code_to_exec, ctx)
        │                             │             └ ScriptRunContext(session_id='06b85b09-d57a-4c30-9062-de6ae8fda417', _enqueue=<bound method ScriptRunner._enqueue_forward_msg ...
        │                             └ <function ScriptRunner._run_script.<locals>.code_to_exec at 0x7330a925aca0>
        └ <function exec_func_with_error_handling at 0x7330aa8e84a0>
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
             └ <function ScriptRunner._run_script.<locals>.code_to_exec at 0x7330a925aca0>
  File "/home/rishabh/Downloads/SIH-Project/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
         │     │      └ <member '__dict__' of 'module' objects>
         │     └ <module '__main__' from 'src/web/app.py'>
         └ <code object <module> at 0x73309005ddb0, file "/home/rishabh/Downloads/SIH-Project/src/web/app.py", line 1>

> File "/home/rishabh/Downloads/SIH-Project/src/web/app.py", line 415, in <module>
    meta = run_pipeline(
           └ <function run_pipeline at 0x733078957b00>

  File "/home/rishabh/Downloads/SIH-Project/src/pipeline.py", line 64, in run_pipeline
    fastp_outputs = run_fastp(
                    └ <function run_fastp at 0x733078957560>

  File "/home/rishabh/Downloads/SIH-Project/src/preprocessing/fastp_wrapper.py", line 63, in run_fastp
    subprocess.run(cmd, check=True)
    │          │   └ ['fastp', '-i', '/tmp/uploaded_files_119077e7/sample.fastq', '-o', '/tmp/interim/sample_clean.fastq.gz', '-w', '4', '-j', '/t...
    │          └ <function run at 0x7330ab219760>
    └ <module 'subprocess' from '/usr/lib/python3.12/subprocess.py'>

  File "/usr/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
          │                  │        │       └ ['fastp', '-i', '/tmp/uploaded_files_119077e7/sample.fastq', '-o', '/tmp/interim/sample_clean.fastq.gz', '-w', '4', '-j', '/t...
          │                  │        └ <Popen: returncode: 255 args: ['fastp', '-i', '/tmp/uploaded_files_119077e7/...>
          │                  └ 255
          └ <class 'subprocess.CalledProcessError'>

subprocess.CalledProcessError: Command '['fastp', '-i', '/tmp/uploaded_files_119077e7/sample.fastq', '-o', '/tmp/interim/sample_clean.fastq.gz', '-w', '4', '-j', '/tmp/interim/fastp_report.json', '-h', '/tmp/interim/fastp_report.html', '-q', '15', '-l', '50']' returned non-zero exit status 255.
2025-09-30 20:30:39.063 | INFO     | src.pipeline:run_pipeline:44 - Starting Stage 1 pipeline job with raw_dir=/tmp/uploaded_files_de95e444
2025-09-30 20:30:39.065 | INFO     | src.preprocessing.fastp_wrapper:run_fastp:62 - Running fastp: fastp -i /tmp/uploaded_files_de95e444/real_sample.fastq -o /tmp/interim/real_sample_clean.fastq.gz -w 4 -j /tmp/interim/fastp_report.json -h /tmp/interim/fastp_report.html -q 15 -l 50
2025-09-30 20:30:40.226 | INFO     | src.preprocessing.dada2_wrapper:run_dada2:31 - Running DADA2: Rscript scripts/run_dada2.R /tmp/interim dada2 /tmp/processed single 2 2 pseudo
2025-09-30 20:54:28.655 | INFO     | src.pipeline:run_pipeline:121 - Metadata written to /tmp/processed/stage1_metadata.json
2025-10-01 13:38:27.142 | INFO     | src.pipeline:run_pipeline:44 - Starting Stage 1 pipeline job with raw_dir=/tmp/uploaded_files_2c19e6dc
2025-10-01 13:38:27.144 | INFO     | src.preprocessing.fastp_wrapper:run_fastp:62 - Running fastp: fastp -i /tmp/uploaded_files_2c19e6dc/real_sample.fastq -o /tmp/interim/real_sample_clean.fastq.gz -w 4 -j /tmp/interim/fastp_report.json -h /tmp/interim/fastp_report.html -q 15 -l 50
2025-10-01 13:38:28.418 | INFO     | src.preprocessing.dada2_wrapper:run_dada2:31 - Running DADA2: Rscript scripts/run_dada2.R /tmp/interim dada2 /tmp/processed single 2 2 pseudo
2025-10-01 13:38:50.863 | INFO     | src.pipeline:run_pipeline:121 - Metadata written to /tmp/processed/stage1_metadata.json
2025-10-01 13:49:33.670 | INFO     | src.pipeline:run_pipeline:44 - Starting Stage 1 pipeline job with raw_dir=/tmp/uploaded_files_e6a918fc
2025-10-01 13:49:33.672 | INFO     | src.preprocessing.fastp_wrapper:run_fastp:62 - Running fastp: fastp -i /tmp/uploaded_files_e6a918fc/real_sample.fastq -o /tmp/interim/real_sample_clean.fastq.gz -w 4 -j /tmp/interim/fastp_report.json -h /tmp/interim/fastp_report.html -q 15 -l 50
2025-10-01 13:49:35.059 | INFO     | src.preprocessing.dada2_wrapper:run_dada2:31 - Running DADA2: Rscript scripts/run_dada2.R /tmp/interim dada2 /tmp/processed single 2 2 pseudo
2025-10-01 13:51:35.801 | INFO     | src.pipeline:run_pipeline:44 - Starting Stage 1 pipeline job with raw_dir=/tmp/uploaded_files_1d82832d
2025-10-01 13:51:35.803 | INFO     | src.preprocessing.fastp_wrapper:run_fastp:62 - Running fastp: fastp -i /tmp/uploaded_files_1d82832d/real_sample.fastq -o /tmp/interim/real_sample_clean.fastq.gz -w 4 -j /tmp/interim/fastp_report.json -h /tmp/interim/fastp_report.html -q 15 -l 50
2025-10-01 13:51:37.455 | INFO     | src.preprocessing.dada2_wrapper:run_dada2:31 - Running DADA2: Rscript scripts/run_dada2.R /tmp/interim dada2 /tmp/processed single 2 2 pseudo
2025-10-01 13:52:01.633 | INFO     | src.pipeline:run_pipeline:121 - Metadata written to /tmp/processed/stage1_metadata.json
2025-10-01 14:12:48.282 | INFO     | src.pipeline:run_pipeline:44 - Starting Stage 1 pipeline job with raw_dir=/tmp/uploaded_files_afb4682b
2025-10-01 14:12:48.285 | INFO     | src.preprocessing.fastp_wrapper:run_fastp:62 - Running fastp: fastp -i /tmp/uploaded_files_afb4682b/real_sample.fastq -o /tmp/interim/real_sample_clean.fastq.gz -w 4 -j /tmp/interim/fastp_report.json -h /tmp/interim/fastp_report.html -q 15 -l 50
2025-10-01 14:12:49.853 | INFO     | src.preprocessing.dada2_wrapper:run_dada2:31 - Running DADA2: Rscript scripts/run_dada2.R /tmp/interim dada2 /tmp/processed single 2 2 pseudo
2025-10-01 14:13:11.146 | INFO     | src.pipeline:run_pipeline:121 - Metadata written to /tmp/processed/stage1_metadata.json
2025-10-01 14:40:47.402 | INFO     | src.pipeline:run_pipeline:44 - Starting Stage 1 pipeline job with raw_dir=/tmp/uploaded_files_a60ff808
2025-10-01 14:40:47.403 | INFO     | src.preprocessing.fastp_wrapper:run_fastp:62 - Running fastp: fastp -i /tmp/uploaded_files_a60ff808/anc_R1.fastq -I /tmp/uploaded_files_a60ff808/anc_R2.fastq -o /tmp/interim/anc_R1_clean.fastq.gz -O /tmp/interim/anc_R2_clean.fastq.gz -w 4 -j /tmp/interim/fastp_report.json -h /tmp/interim/fastp_report.html -q 15 -l 50 --detect_adapter_for_pe
2025-10-01 14:41:14.333 | INFO     | src.preprocessing.dada2_wrapper:run_dada2:31 - Running DADA2: Rscript scripts/run_dada2.R /tmp/interim dada2 /tmp/processed paired 2 2 pseudo
2025-10-01 15:27:51.474 | INFO     | src.pipeline:run_pipeline:121 - Metadata written to /tmp/processed/stage1_metadata.json
2025-10-01 16:14:36.873 | INFO     | src.pipeline:run_pipeline:44 - Starting Stage 1 pipeline job with raw_dir=/tmp/uploaded_files_dec9b6ab
2025-10-01 16:14:36.874 | INFO     | src.preprocessing.fastp_wrapper:run_fastp:62 - Running fastp: fastp -i /tmp/uploaded_files_dec9b6ab/real_sample.fastq -o /tmp/interim/real_sample_clean.fastq.gz -w 4 -j /tmp/interim/fastp_report.json -h /tmp/interim/fastp_report.html -q 15 -l 50
2025-10-01 16:14:37.839 | INFO     | src.preprocessing.dada2_wrapper:run_dada2:31 - Running DADA2: Rscript scripts/run_dada2.R /tmp/interim dada2 /tmp/processed single 2 2 pseudo
2025-10-01 16:41:06.899 | INFO     | src.pipeline:run_pipeline:121 - Metadata written to /tmp/processed/stage1_metadata.json
2025-10-01 16:50:53.209 | INFO     | src.pipeline:run_pipeline:44 - Starting Stage 1 pipeline job with raw_dir=/tmp/uploaded_files_6ef1930c
2025-10-01 16:50:53.249 | INFO     | src.preprocessing.fastp_wrapper:run_fastp:62 - Running fastp: fastp -i /tmp/uploaded_files_6ef1930c/anc_R1.fastq -o /tmp/interim/anc_R1_clean.fastq.gz -w 4 -j /tmp/interim/fastp_report.json -h /tmp/interim/fastp_report.html -q 15 -l 50
2025-10-01 16:51:03.794 | INFO     | src.preprocessing.dada2_wrapper:run_dada2:31 - Running DADA2: Rscript scripts/run_dada2.R /tmp/interim dada2 /tmp/processed single 2 2 pseudo
2025-10-01 17:18:34.509 | INFO     | src.pipeline:run_pipeline:121 - Metadata written to /tmp/processed/stage1_metadata.json
2025-10-01 17:24:52.876 | INFO     | src.pipeline:run_pipeline:44 - Starting Stage 1 pipeline job with raw_dir=/tmp/uploaded_files_1867bdf1
2025-10-01 17:24:52.877 | INFO     | src.preprocessing.fastp_wrapper:run_fastp:62 - Running fastp: fastp -i /tmp/uploaded_files_1867bdf1/anc_R1.fastq -I /tmp/uploaded_files_1867bdf1/anc_R2.fastq -o /tmp/interim/anc_R1_clean.fastq.gz -O /tmp/interim/anc_R2_clean.fastq.gz -w 4 -j /tmp/interim/fastp_report.json -h /tmp/interim/fastp_report.html -q 15 -l 50 --detect_adapter_for_pe
2025-10-01 17:25:08.415 | INFO     | src.preprocessing.dada2_wrapper:run_dada2:31 - Running DADA2: Rscript scripts/run_dada2.R /tmp/interim dada2 /tmp/processed paired 2 2 pseudo
2025-10-01 17:58:07.882 | INFO     | src.pipeline:run_pipeline:121 - Metadata written to /tmp/processed/stage1_metadata.json
